// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.3
// source: api_chain.proto

package api

import (
	_ "github.com/ysugimoto/grpc-graphql-gateway/graphql"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainRequest) Reset() {
	*x = ChainRequest{}
	mi := &file_api_chain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainRequest) ProtoMessage() {}

func (x *ChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainRequest.ProtoReflect.Descriptor instead.
func (*ChainRequest) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{0}
}

type VotingResultMeta struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalCandidates    uint64                 `protobuf:"varint,1,opt,name=totalCandidates,proto3" json:"totalCandidates,omitempty"`      // total candidates
	TotalWeightedVotes string                 `protobuf:"bytes,2,opt,name=totalWeightedVotes,proto3" json:"totalWeightedVotes,omitempty"` // total weighted votes
	VotedTokens        string                 `protobuf:"bytes,3,opt,name=votedTokens,proto3" json:"votedTokens,omitempty"`               // voted tokens
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VotingResultMeta) Reset() {
	*x = VotingResultMeta{}
	mi := &file_api_chain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VotingResultMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VotingResultMeta) ProtoMessage() {}

func (x *VotingResultMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VotingResultMeta.ProtoReflect.Descriptor instead.
func (*VotingResultMeta) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{1}
}

func (x *VotingResultMeta) GetTotalCandidates() uint64 {
	if x != nil {
		return x.TotalCandidates
	}
	return 0
}

func (x *VotingResultMeta) GetTotalWeightedVotes() string {
	if x != nil {
		return x.TotalWeightedVotes
	}
	return ""
}

func (x *VotingResultMeta) GetVotedTokens() string {
	if x != nil {
		return x.VotedTokens
	}
	return ""
}

type ChainResponse struct {
	state                              protoimpl.MessageState `protogen:"open.v1"`
	MostRecentEpoch                    uint64                 `protobuf:"varint,1,opt,name=mostRecentEpoch,proto3" json:"mostRecentEpoch,omitempty"`                                      // most recent epoch
	MostRecentBlockHeight              uint64                 `protobuf:"varint,2,opt,name=mostRecentBlockHeight,proto3" json:"mostRecentBlockHeight,omitempty"`                          // most recent block height
	TotalSupply                        string                 `protobuf:"bytes,3,opt,name=totalSupply,proto3" json:"totalSupply,omitempty"`                                               // total supply
	TotalCirculatingSupply             string                 `protobuf:"bytes,4,opt,name=totalCirculatingSupply,proto3" json:"totalCirculatingSupply,omitempty"`                         // total circulating supply
	TotalCirculatingSupplyNoRewardPool string                 `protobuf:"bytes,5,opt,name=totalCirculatingSupplyNoRewardPool,proto3" json:"totalCirculatingSupplyNoRewardPool,omitempty"` // total circulating supply no reward pool
	VotingResultMeta                   *VotingResultMeta      `protobuf:"bytes,6,opt,name=votingResultMeta,proto3" json:"votingResultMeta,omitempty"`                                     // voting result meta
	ExactCirculatingSupply             string                 `protobuf:"bytes,7,opt,name=exactCirculatingSupply,proto3" json:"exactCirculatingSupply,omitempty"`                         // exact circulating supply
	Rewards                            *ChainResponse_Rewards `protobuf:"bytes,8,opt,name=rewards,proto3" json:"rewards,omitempty"`                                                       // rewards
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *ChainResponse) Reset() {
	*x = ChainResponse{}
	mi := &file_api_chain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainResponse) ProtoMessage() {}

func (x *ChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainResponse.ProtoReflect.Descriptor instead.
func (*ChainResponse) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{2}
}

func (x *ChainResponse) GetMostRecentEpoch() uint64 {
	if x != nil {
		return x.MostRecentEpoch
	}
	return 0
}

func (x *ChainResponse) GetMostRecentBlockHeight() uint64 {
	if x != nil {
		return x.MostRecentBlockHeight
	}
	return 0
}

func (x *ChainResponse) GetTotalSupply() string {
	if x != nil {
		return x.TotalSupply
	}
	return ""
}

func (x *ChainResponse) GetTotalCirculatingSupply() string {
	if x != nil {
		return x.TotalCirculatingSupply
	}
	return ""
}

func (x *ChainResponse) GetTotalCirculatingSupplyNoRewardPool() string {
	if x != nil {
		return x.TotalCirculatingSupplyNoRewardPool
	}
	return ""
}

func (x *ChainResponse) GetVotingResultMeta() *VotingResultMeta {
	if x != nil {
		return x.VotingResultMeta
	}
	return nil
}

func (x *ChainResponse) GetExactCirculatingSupply() string {
	if x != nil {
		return x.ExactCirculatingSupply
	}
	return ""
}

func (x *ChainResponse) GetRewards() *ChainResponse_Rewards {
	if x != nil {
		return x.Rewards
	}
	return nil
}

type MostRecentTPSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockWindow   uint64                 `protobuf:"varint,1,opt,name=blockWindow,proto3" json:"blockWindow,omitempty"` // number of last blocks that are backtracked to compute TPS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MostRecentTPSRequest) Reset() {
	*x = MostRecentTPSRequest{}
	mi := &file_api_chain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MostRecentTPSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MostRecentTPSRequest) ProtoMessage() {}

func (x *MostRecentTPSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MostRecentTPSRequest.ProtoReflect.Descriptor instead.
func (*MostRecentTPSRequest) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{3}
}

func (x *MostRecentTPSRequest) GetBlockWindow() uint64 {
	if x != nil {
		return x.BlockWindow
	}
	return 0
}

type MostRecentTPSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MostRecentTPS float64                `protobuf:"fixed64,1,opt,name=mostRecentTPS,proto3" json:"mostRecentTPS,omitempty"` // latest transactions per second
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MostRecentTPSResponse) Reset() {
	*x = MostRecentTPSResponse{}
	mi := &file_api_chain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MostRecentTPSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MostRecentTPSResponse) ProtoMessage() {}

func (x *MostRecentTPSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MostRecentTPSResponse.ProtoReflect.Descriptor instead.
func (*MostRecentTPSResponse) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{4}
}

func (x *MostRecentTPSResponse) GetMostRecentTPS() float64 {
	if x != nil {
		return x.MostRecentTPS
	}
	return 0
}

type NumberOfActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartEpoch    uint64                 `protobuf:"varint,1,opt,name=startEpoch,proto3" json:"startEpoch,omitempty"` // starting epoch number
	EpochCount    uint64                 `protobuf:"varint,2,opt,name=epochCount,proto3" json:"epochCount,omitempty"` // epoch count
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberOfActionsRequest) Reset() {
	*x = NumberOfActionsRequest{}
	mi := &file_api_chain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberOfActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberOfActionsRequest) ProtoMessage() {}

func (x *NumberOfActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberOfActionsRequest.ProtoReflect.Descriptor instead.
func (*NumberOfActionsRequest) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{5}
}

func (x *NumberOfActionsRequest) GetStartEpoch() uint64 {
	if x != nil {
		return x.StartEpoch
	}
	return 0
}

func (x *NumberOfActionsRequest) GetEpochCount() uint64 {
	if x != nil {
		return x.EpochCount
	}
	return 0
}

type NumberOfActionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exist         bool                   `protobuf:"varint,1,opt,name=exist,proto3" json:"exist,omitempty"` // whether the starting epoch number is less than the most recent epoch number
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // number of actions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberOfActionsResponse) Reset() {
	*x = NumberOfActionsResponse{}
	mi := &file_api_chain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberOfActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberOfActionsResponse) ProtoMessage() {}

func (x *NumberOfActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberOfActionsResponse.ProtoReflect.Descriptor instead.
func (*NumberOfActionsResponse) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{6}
}

func (x *NumberOfActionsResponse) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

func (x *NumberOfActionsResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TotalTransferredTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartEpoch    uint64                 `protobuf:"varint,1,opt,name=startEpoch,proto3" json:"startEpoch,omitempty"` // starting epoch number
	EpochCount    uint64                 `protobuf:"varint,2,opt,name=epochCount,proto3" json:"epochCount,omitempty"` // epoch count
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TotalTransferredTokensRequest) Reset() {
	*x = TotalTransferredTokensRequest{}
	mi := &file_api_chain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalTransferredTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalTransferredTokensRequest) ProtoMessage() {}

func (x *TotalTransferredTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalTransferredTokensRequest.ProtoReflect.Descriptor instead.
func (*TotalTransferredTokensRequest) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{7}
}

func (x *TotalTransferredTokensRequest) GetStartEpoch() uint64 {
	if x != nil {
		return x.StartEpoch
	}
	return 0
}

func (x *TotalTransferredTokensRequest) GetEpochCount() uint64 {
	if x != nil {
		return x.EpochCount
	}
	return 0
}

type TotalTransferredTokensResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TotalTransferredTokens string                 `protobuf:"bytes,1,opt,name=totalTransferredTokens,proto3" json:"totalTransferredTokens,omitempty"` // total tranferred tokens
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TotalTransferredTokensResponse) Reset() {
	*x = TotalTransferredTokensResponse{}
	mi := &file_api_chain_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalTransferredTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalTransferredTokensResponse) ProtoMessage() {}

func (x *TotalTransferredTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalTransferredTokensResponse.ProtoReflect.Descriptor instead.
func (*TotalTransferredTokensResponse) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{8}
}

func (x *TotalTransferredTokensResponse) GetTotalTransferredTokens() string {
	if x != nil {
		return x.TotalTransferredTokens
	}
	return ""
}

type BlockSizeByHeightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"` // block height
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockSizeByHeightRequest) Reset() {
	*x = BlockSizeByHeightRequest{}
	mi := &file_api_chain_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSizeByHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSizeByHeightRequest) ProtoMessage() {}

func (x *BlockSizeByHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSizeByHeightRequest.ProtoReflect.Descriptor instead.
func (*BlockSizeByHeightRequest) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{9}
}

func (x *BlockSizeByHeightRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type BlockSizeByHeightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockSize     float64                `protobuf:"fixed64,2,opt,name=blockSize,proto3" json:"blockSize,omitempty"`       // size
	ServerVersion string                 `protobuf:"bytes,3,opt,name=serverVersion,proto3" json:"serverVersion,omitempty"` // version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockSizeByHeightResponse) Reset() {
	*x = BlockSizeByHeightResponse{}
	mi := &file_api_chain_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSizeByHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSizeByHeightResponse) ProtoMessage() {}

func (x *BlockSizeByHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSizeByHeightResponse.ProtoReflect.Descriptor instead.
func (*BlockSizeByHeightResponse) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{10}
}

func (x *BlockSizeByHeightResponse) GetBlockSize() float64 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *BlockSizeByHeightResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

type GetLatestBlockHeightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestBlockHeightRequest) Reset() {
	*x = GetLatestBlockHeightRequest{}
	mi := &file_api_chain_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestBlockHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestBlockHeightRequest) ProtoMessage() {}

func (x *GetLatestBlockHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestBlockHeightRequest.ProtoReflect.Descriptor instead.
func (*GetLatestBlockHeightRequest) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{11}
}

type GetLatestBlockHeightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"` // latest block height
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestBlockHeightResponse) Reset() {
	*x = GetLatestBlockHeightResponse{}
	mi := &file_api_chain_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestBlockHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestBlockHeightResponse) ProtoMessage() {}

func (x *GetLatestBlockHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestBlockHeightResponse.ProtoReflect.Descriptor instead.
func (*GetLatestBlockHeightResponse) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{12}
}

func (x *GetLatestBlockHeightResponse) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type BlockInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BlockHeight     uint64                 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`            // block height
	BlockHash       string                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`                   // block hash
	ProducerAddress string                 `protobuf:"bytes,3,opt,name=producer_address,json=producerAddress,proto3" json:"producer_address,omitempty"` // producer address
	NumActions      uint64                 `protobuf:"varint,4,opt,name=num_actions,json=numActions,proto3" json:"num_actions,omitempty"`               // number of actions
	Timestamp       int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                   // block timestamp (unix timestamp)
	GasConsumed     uint64                 `protobuf:"varint,6,opt,name=gas_consumed,json=gasConsumed,proto3" json:"gas_consumed,omitempty"`            // gas consumed
	ProducerName    string                 `protobuf:"bytes,7,opt,name=producer_name,json=producerName,proto3" json:"producer_name,omitempty"`          // producer name
	BlockReward     string                 `protobuf:"bytes,8,opt,name=block_reward,json=blockReward,proto3" json:"block_reward,omitempty"`             // block reward
	EpochNum        uint64                 `protobuf:"varint,9,opt,name=epoch_num,json=epochNum,proto3" json:"epoch_num,omitempty"`                     // epoch number
	PriorityBonus   string                 `protobuf:"bytes,10,opt,name=priority_bonus,json=priorityBonus,proto3" json:"priority_bonus,omitempty"`      // priority bonus
	BaseFee         string                 `protobuf:"bytes,11,opt,name=base_fee,json=baseFee,proto3" json:"base_fee,omitempty"`                        // base fee
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlockInfo) Reset() {
	*x = BlockInfo{}
	mi := &file_api_chain_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockInfo) ProtoMessage() {}

func (x *BlockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockInfo.ProtoReflect.Descriptor instead.
func (*BlockInfo) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{13}
}

func (x *BlockInfo) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *BlockInfo) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *BlockInfo) GetProducerAddress() string {
	if x != nil {
		return x.ProducerAddress
	}
	return ""
}

func (x *BlockInfo) GetNumActions() uint64 {
	if x != nil {
		return x.NumActions
	}
	return 0
}

func (x *BlockInfo) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlockInfo) GetGasConsumed() uint64 {
	if x != nil {
		return x.GasConsumed
	}
	return 0
}

func (x *BlockInfo) GetProducerName() string {
	if x != nil {
		return x.ProducerName
	}
	return ""
}

func (x *BlockInfo) GetBlockReward() string {
	if x != nil {
		return x.BlockReward
	}
	return ""
}

func (x *BlockInfo) GetEpochNum() uint64 {
	if x != nil {
		return x.EpochNum
	}
	return 0
}

func (x *BlockInfo) GetPriorityBonus() string {
	if x != nil {
		return x.PriorityBonus
	}
	return ""
}

func (x *BlockInfo) GetBaseFee() string {
	if x != nil {
		return x.BaseFee
	}
	return ""
}

type GetBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint64                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`   // page number (starts from 1)
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // number of blocks per page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlocksRequest) Reset() {
	*x = GetBlocksRequest{}
	mi := &file_api_chain_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksRequest) ProtoMessage() {}

func (x *GetBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksRequest.ProtoReflect.Descriptor instead.
func (*GetBlocksRequest) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{14}
}

func (x *GetBlocksRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetBlocksRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*BlockInfo           `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"` // list of blocks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlocksResponse) Reset() {
	*x = GetBlocksResponse{}
	mi := &file_api_chain_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksResponse) ProtoMessage() {}

func (x *GetBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksResponse.ProtoReflect.Descriptor instead.
func (*GetBlocksResponse) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{15}
}

func (x *GetBlocksResponse) GetBlocks() []*BlockInfo {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type GetBlockByHeightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"` // block height
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockByHeightRequest) Reset() {
	*x = GetBlockByHeightRequest{}
	mi := &file_api_chain_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockByHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockByHeightRequest) ProtoMessage() {}

func (x *GetBlockByHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockByHeightRequest.ProtoReflect.Descriptor instead.
func (*GetBlockByHeightRequest) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{16}
}

func (x *GetBlockByHeightRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetBlockByHeightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *BlockInfo             `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"` // block info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockByHeightResponse) Reset() {
	*x = GetBlockByHeightResponse{}
	mi := &file_api_chain_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockByHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockByHeightResponse) ProtoMessage() {}

func (x *GetBlockByHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockByHeightResponse.ProtoReflect.Descriptor instead.
func (*GetBlockByHeightResponse) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{17}
}

func (x *GetBlockByHeightResponse) GetBlock() *BlockInfo {
	if x != nil {
		return x.Block
	}
	return nil
}

type GetBlockInfoByActionHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionHash    string                 `protobuf:"bytes,1,opt,name=action_hash,json=actionHash,proto3" json:"action_hash,omitempty"` // action hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockInfoByActionHashRequest) Reset() {
	*x = GetBlockInfoByActionHashRequest{}
	mi := &file_api_chain_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockInfoByActionHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockInfoByActionHashRequest) ProtoMessage() {}

func (x *GetBlockInfoByActionHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockInfoByActionHashRequest.ProtoReflect.Descriptor instead.
func (*GetBlockInfoByActionHashRequest) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{18}
}

func (x *GetBlockInfoByActionHashRequest) GetActionHash() string {
	if x != nil {
		return x.ActionHash
	}
	return ""
}

type GetBlockInfoByActionHashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseFee       string                 `protobuf:"bytes,1,opt,name=base_fee,json=baseFee,proto3" json:"base_fee,omitempty"` // base fee
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockInfoByActionHashResponse) Reset() {
	*x = GetBlockInfoByActionHashResponse{}
	mi := &file_api_chain_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockInfoByActionHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockInfoByActionHashResponse) ProtoMessage() {}

func (x *GetBlockInfoByActionHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockInfoByActionHashResponse.ProtoReflect.Descriptor instead.
func (*GetBlockInfoByActionHashResponse) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{19}
}

func (x *GetBlockInfoByActionHashResponse) GetBaseFee() string {
	if x != nil {
		return x.BaseFee
	}
	return ""
}

type BlockReceipt struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                            // receipt id
	BlockHeight        uint64                 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`                       // block height
	ActionHash         string                 `protobuf:"bytes,3,opt,name=action_hash,json=actionHash,proto3" json:"action_hash,omitempty"`                           // action hash
	GasConsumed        uint64                 `protobuf:"varint,4,opt,name=gas_consumed,json=gasConsumed,proto3" json:"gas_consumed,omitempty"`                       // gas consumed
	ContractAddress    string                 `protobuf:"bytes,5,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`            // contract address
	Status             bool                   `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`                                                    // status
	ExecutionRevertMsg string                 `protobuf:"bytes,7,opt,name=execution_revert_msg,json=executionRevertMsg,proto3" json:"execution_revert_msg,omitempty"` // execution revert message
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BlockReceipt) Reset() {
	*x = BlockReceipt{}
	mi := &file_api_chain_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockReceipt) ProtoMessage() {}

func (x *BlockReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockReceipt.ProtoReflect.Descriptor instead.
func (*BlockReceipt) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{20}
}

func (x *BlockReceipt) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BlockReceipt) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *BlockReceipt) GetActionHash() string {
	if x != nil {
		return x.ActionHash
	}
	return ""
}

func (x *BlockReceipt) GetGasConsumed() uint64 {
	if x != nil {
		return x.GasConsumed
	}
	return 0
}

func (x *BlockReceipt) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *BlockReceipt) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *BlockReceipt) GetExecutionRevertMsg() string {
	if x != nil {
		return x.ExecutionRevertMsg
	}
	return ""
}

type GetBlockReceiptByActionHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionHash    string                 `protobuf:"bytes,1,opt,name=action_hash,json=actionHash,proto3" json:"action_hash,omitempty"` // action hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockReceiptByActionHashRequest) Reset() {
	*x = GetBlockReceiptByActionHashRequest{}
	mi := &file_api_chain_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockReceiptByActionHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockReceiptByActionHashRequest) ProtoMessage() {}

func (x *GetBlockReceiptByActionHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockReceiptByActionHashRequest.ProtoReflect.Descriptor instead.
func (*GetBlockReceiptByActionHashRequest) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{21}
}

func (x *GetBlockReceiptByActionHashRequest) GetActionHash() string {
	if x != nil {
		return x.ActionHash
	}
	return ""
}

type GetBlockReceiptByActionHashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipt       *BlockReceipt          `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"` // block receipt
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockReceiptByActionHashResponse) Reset() {
	*x = GetBlockReceiptByActionHashResponse{}
	mi := &file_api_chain_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockReceiptByActionHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockReceiptByActionHashResponse) ProtoMessage() {}

func (x *GetBlockReceiptByActionHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockReceiptByActionHashResponse.ProtoReflect.Descriptor instead.
func (*GetBlockReceiptByActionHashResponse) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{22}
}

func (x *GetBlockReceiptByActionHashResponse) GetReceipt() *BlockReceipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type ChainResponse_Rewards struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalBalance   string                 `protobuf:"bytes,1,opt,name=totalBalance,proto3" json:"totalBalance,omitempty"`     // total balance
	TotalUnclaimed string                 `protobuf:"bytes,2,opt,name=totalUnclaimed,proto3" json:"totalUnclaimed,omitempty"` // total unclaimed
	TotalAvailable string                 `protobuf:"bytes,3,opt,name=totalAvailable,proto3" json:"totalAvailable,omitempty"` // total available
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChainResponse_Rewards) Reset() {
	*x = ChainResponse_Rewards{}
	mi := &file_api_chain_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainResponse_Rewards) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainResponse_Rewards) ProtoMessage() {}

func (x *ChainResponse_Rewards) ProtoReflect() protoreflect.Message {
	mi := &file_api_chain_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainResponse_Rewards.ProtoReflect.Descriptor instead.
func (*ChainResponse_Rewards) Descriptor() ([]byte, []int) {
	return file_api_chain_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ChainResponse_Rewards) GetTotalBalance() string {
	if x != nil {
		return x.TotalBalance
	}
	return ""
}

func (x *ChainResponse_Rewards) GetTotalUnclaimed() string {
	if x != nil {
		return x.TotalUnclaimed
	}
	return ""
}

func (x *ChainResponse_Rewards) GetTotalAvailable() string {
	if x != nil {
		return x.TotalAvailable
	}
	return ""
}

var File_api_chain_proto protoreflect.FileDescriptor

const file_api_chain_proto_rawDesc = "" +
	"\n" +
	"\x0fapi_chain.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x15include/graphql.proto\"\x0e\n" +
	"\fChainRequest\"\x8e\x01\n" +
	"\x10VotingResultMeta\x12(\n" +
	"\x0ftotalCandidates\x18\x01 \x01(\x04R\x0ftotalCandidates\x12.\n" +
	"\x12totalWeightedVotes\x18\x02 \x01(\tR\x12totalWeightedVotes\x12 \n" +
	"\vvotedTokens\x18\x03 \x01(\tR\vvotedTokens\"\xc9\x04\n" +
	"\rChainResponse\x12(\n" +
	"\x0fmostRecentEpoch\x18\x01 \x01(\x04R\x0fmostRecentEpoch\x124\n" +
	"\x15mostRecentBlockHeight\x18\x02 \x01(\x04R\x15mostRecentBlockHeight\x12 \n" +
	"\vtotalSupply\x18\x03 \x01(\tR\vtotalSupply\x126\n" +
	"\x16totalCirculatingSupply\x18\x04 \x01(\tR\x16totalCirculatingSupply\x12N\n" +
	"\"totalCirculatingSupplyNoRewardPool\x18\x05 \x01(\tR\"totalCirculatingSupplyNoRewardPool\x12A\n" +
	"\x10votingResultMeta\x18\x06 \x01(\v2\x15.api.VotingResultMetaR\x10votingResultMeta\x126\n" +
	"\x16exactCirculatingSupply\x18\a \x01(\tR\x16exactCirculatingSupply\x124\n" +
	"\arewards\x18\b \x01(\v2\x1a.api.ChainResponse.RewardsR\arewards\x1a}\n" +
	"\aRewards\x12\"\n" +
	"\ftotalBalance\x18\x01 \x01(\tR\ftotalBalance\x12&\n" +
	"\x0etotalUnclaimed\x18\x02 \x01(\tR\x0etotalUnclaimed\x12&\n" +
	"\x0etotalAvailable\x18\x03 \x01(\tR\x0etotalAvailable\"8\n" +
	"\x14MostRecentTPSRequest\x12 \n" +
	"\vblockWindow\x18\x01 \x01(\x04R\vblockWindow\"=\n" +
	"\x15MostRecentTPSResponse\x12$\n" +
	"\rmostRecentTPS\x18\x01 \x01(\x01R\rmostRecentTPS\"X\n" +
	"\x16NumberOfActionsRequest\x12\x1e\n" +
	"\n" +
	"startEpoch\x18\x01 \x01(\x04R\n" +
	"startEpoch\x12\x1e\n" +
	"\n" +
	"epochCount\x18\x02 \x01(\x04R\n" +
	"epochCount\"E\n" +
	"\x17NumberOfActionsResponse\x12\x14\n" +
	"\x05exist\x18\x01 \x01(\bR\x05exist\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"_\n" +
	"\x1dTotalTransferredTokensRequest\x12\x1e\n" +
	"\n" +
	"startEpoch\x18\x01 \x01(\x04R\n" +
	"startEpoch\x12\x1e\n" +
	"\n" +
	"epochCount\x18\x02 \x01(\x04R\n" +
	"epochCount\"X\n" +
	"\x1eTotalTransferredTokensResponse\x126\n" +
	"\x16totalTransferredTokens\x18\x01 \x01(\tR\x16totalTransferredTokens\"2\n" +
	"\x18BlockSizeByHeightRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\"_\n" +
	"\x19BlockSizeByHeightResponse\x12\x1c\n" +
	"\tblockSize\x18\x02 \x01(\x01R\tblockSize\x12$\n" +
	"\rserverVersion\x18\x03 \x01(\tR\rserverVersion\"\x1d\n" +
	"\x1bGetLatestBlockHeightRequest\"6\n" +
	"\x1cGetLatestBlockHeightResponse\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\"\x81\x03\n" +
	"\tBlockInfo\x12!\n" +
	"\fblock_height\x18\x01 \x01(\x04R\vblockHeight\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\tR\tblockHash\x12)\n" +
	"\x10producer_address\x18\x03 \x01(\tR\x0fproducerAddress\x12\x1f\n" +
	"\vnum_actions\x18\x04 \x01(\x04R\n" +
	"numActions\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12!\n" +
	"\fgas_consumed\x18\x06 \x01(\x04R\vgasConsumed\x12#\n" +
	"\rproducer_name\x18\a \x01(\tR\fproducerName\x12!\n" +
	"\fblock_reward\x18\b \x01(\tR\vblockReward\x12\x1b\n" +
	"\tepoch_num\x18\t \x01(\x04R\bepochNum\x12%\n" +
	"\x0epriority_bonus\x18\n" +
	" \x01(\tR\rpriorityBonus\x12\x19\n" +
	"\bbase_fee\x18\v \x01(\tR\abaseFee\"<\n" +
	"\x10GetBlocksRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x04R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\";\n" +
	"\x11GetBlocksResponse\x12&\n" +
	"\x06blocks\x18\x01 \x03(\v2\x0e.api.BlockInfoR\x06blocks\"1\n" +
	"\x17GetBlockByHeightRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\"@\n" +
	"\x18GetBlockByHeightResponse\x12$\n" +
	"\x05block\x18\x01 \x01(\v2\x0e.api.BlockInfoR\x05block\"B\n" +
	"\x1fGetBlockInfoByActionHashRequest\x12\x1f\n" +
	"\vaction_hash\x18\x01 \x01(\tR\n" +
	"actionHash\"=\n" +
	" GetBlockInfoByActionHashResponse\x12\x19\n" +
	"\bbase_fee\x18\x01 \x01(\tR\abaseFee\"\xfa\x01\n" +
	"\fBlockReceipt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\fblock_height\x18\x02 \x01(\x04R\vblockHeight\x12\x1f\n" +
	"\vaction_hash\x18\x03 \x01(\tR\n" +
	"actionHash\x12!\n" +
	"\fgas_consumed\x18\x04 \x01(\x04R\vgasConsumed\x12)\n" +
	"\x10contract_address\x18\x05 \x01(\tR\x0fcontractAddress\x12\x16\n" +
	"\x06status\x18\x06 \x01(\bR\x06status\x120\n" +
	"\x14execution_revert_msg\x18\a \x01(\tR\x12executionRevertMsg\"E\n" +
	"\"GetBlockReceiptByActionHashRequest\x12\x1f\n" +
	"\vaction_hash\x18\x01 \x01(\tR\n" +
	"actionHash\"R\n" +
	"#GetBlockReceiptByActionHashResponse\x12+\n" +
	"\areceipt\x18\x01 \x01(\v2\x11.api.BlockReceiptR\areceipt2\x90\f\n" +
	"\fChainService\x12\\\n" +
	"\x05Chain\x12\x11.api.ChainRequest\x1a\x12.api.ChainResponse\",\xbaC\a\x12\x05Chain\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api.ChainService.Chain\x12\x84\x01\n" +
	"\rMostRecentTPS\x12\x19.api.MostRecentTPSRequest\x1a\x1a.api.MostRecentTPSResponse\"<\xbaC\x0f\x12\rMostRecentTPS\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api.ChainService.MostRecentTPS\x12\x8e\x01\n" +
	"\x0fNumberOfActions\x12\x1b.api.NumberOfActionsRequest\x1a\x1c.api.NumberOfActionsResponse\"@\xbaC\x11\x12\x0fNumberOfActions\x82\xd3\xe4\x93\x02&:\x01*\"!/api.ChainService.NumberOfActions\x12\xb1\x01\n" +
	"\x16TotalTransferredTokens\x12\".api.TotalTransferredTokensRequest\x1a#.api.TotalTransferredTokensResponse\"N\xbaC\x18\x12\x16TotalTransferredTokens\x82\xd3\xe4\x93\x02-:\x01*\"(/api.ChainService.TotalTransferredTokens\x12\x98\x01\n" +
	"\x11BlockSizeByHeight\x12\x1d.api.BlockSizeByHeightRequest\x1a\x1e.api.BlockSizeByHeightResponse\"D\xbaC\x13\x12\x11BlockSizeByHeight\x82\xd3\xe4\x93\x02(:\x01*\"#/api.ChainService.BlockSizeByHeight\x12\xa7\x01\n" +
	"\x14GetLatestBlockHeight\x12 .api.GetLatestBlockHeightRequest\x1a!.api.GetLatestBlockHeightResponse\"J\xbaC\x16\x12\x14GetLatestBlockHeight\x82\xd3\xe4\x93\x02+:\x01*\"&/api.ChainService.GetLatestBlockHeight\x12p\n" +
	"\tGetBlocks\x12\x15.api.GetBlocksRequest\x1a\x16.api.GetBlocksResponse\"4\xbaC\v\x12\tGetBlocks\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api.ChainService.GetBlocks\x12\x93\x01\n" +
	"\x10GetBlockByHeight\x12\x1c.api.GetBlockByHeightRequest\x1a\x1d.api.GetBlockByHeightResponse\"B\xbaC\x12\x12\x10GetBlockByHeight\x82\xd3\xe4\x93\x02':\x01*\"\"/api.ChainService.GetBlockByHeight\x12\xbb\x01\n" +
	"\x18GetBlockInfoByActionHash\x12$.api.GetBlockInfoByActionHashRequest\x1a%.api.GetBlockInfoByActionHashResponse\"R\xbaC\x1a\x12\x18GetBlockInfoByActionHash\x82\xd3\xe4\x93\x02/:\x01*\"*/api.ChainService.GetBlockInfoByActionHash\x12\xca\x01\n" +
	"\x1bGetBlockReceiptByActionHash\x12'.api.GetBlockReceiptByActionHashRequest\x1a(.api.GetBlockReceiptByActionHashResponse\"X\xbaC\x1d\x12\x1bGetBlockReceiptByActionHash\x82\xd3\xe4\x93\x022:\x01*\"-/api.ChainService.GetBlockReceiptByActionHashB\aZ\x05./apib\x06proto3"

var (
	file_api_chain_proto_rawDescOnce sync.Once
	file_api_chain_proto_rawDescData []byte
)

func file_api_chain_proto_rawDescGZIP() []byte {
	file_api_chain_proto_rawDescOnce.Do(func() {
		file_api_chain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_chain_proto_rawDesc), len(file_api_chain_proto_rawDesc)))
	})
	return file_api_chain_proto_rawDescData
}

var file_api_chain_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_chain_proto_goTypes = []any{
	(*ChainRequest)(nil),                        // 0: api.ChainRequest
	(*VotingResultMeta)(nil),                    // 1: api.VotingResultMeta
	(*ChainResponse)(nil),                       // 2: api.ChainResponse
	(*MostRecentTPSRequest)(nil),                // 3: api.MostRecentTPSRequest
	(*MostRecentTPSResponse)(nil),               // 4: api.MostRecentTPSResponse
	(*NumberOfActionsRequest)(nil),              // 5: api.NumberOfActionsRequest
	(*NumberOfActionsResponse)(nil),             // 6: api.NumberOfActionsResponse
	(*TotalTransferredTokensRequest)(nil),       // 7: api.TotalTransferredTokensRequest
	(*TotalTransferredTokensResponse)(nil),      // 8: api.TotalTransferredTokensResponse
	(*BlockSizeByHeightRequest)(nil),            // 9: api.BlockSizeByHeightRequest
	(*BlockSizeByHeightResponse)(nil),           // 10: api.BlockSizeByHeightResponse
	(*GetLatestBlockHeightRequest)(nil),         // 11: api.GetLatestBlockHeightRequest
	(*GetLatestBlockHeightResponse)(nil),        // 12: api.GetLatestBlockHeightResponse
	(*BlockInfo)(nil),                           // 13: api.BlockInfo
	(*GetBlocksRequest)(nil),                    // 14: api.GetBlocksRequest
	(*GetBlocksResponse)(nil),                   // 15: api.GetBlocksResponse
	(*GetBlockByHeightRequest)(nil),             // 16: api.GetBlockByHeightRequest
	(*GetBlockByHeightResponse)(nil),            // 17: api.GetBlockByHeightResponse
	(*GetBlockInfoByActionHashRequest)(nil),     // 18: api.GetBlockInfoByActionHashRequest
	(*GetBlockInfoByActionHashResponse)(nil),    // 19: api.GetBlockInfoByActionHashResponse
	(*BlockReceipt)(nil),                        // 20: api.BlockReceipt
	(*GetBlockReceiptByActionHashRequest)(nil),  // 21: api.GetBlockReceiptByActionHashRequest
	(*GetBlockReceiptByActionHashResponse)(nil), // 22: api.GetBlockReceiptByActionHashResponse
	(*ChainResponse_Rewards)(nil),               // 23: api.ChainResponse.Rewards
}
var file_api_chain_proto_depIdxs = []int32{
	1,  // 0: api.ChainResponse.votingResultMeta:type_name -> api.VotingResultMeta
	23, // 1: api.ChainResponse.rewards:type_name -> api.ChainResponse.Rewards
	13, // 2: api.GetBlocksResponse.blocks:type_name -> api.BlockInfo
	13, // 3: api.GetBlockByHeightResponse.block:type_name -> api.BlockInfo
	20, // 4: api.GetBlockReceiptByActionHashResponse.receipt:type_name -> api.BlockReceipt
	0,  // 5: api.ChainService.Chain:input_type -> api.ChainRequest
	3,  // 6: api.ChainService.MostRecentTPS:input_type -> api.MostRecentTPSRequest
	5,  // 7: api.ChainService.NumberOfActions:input_type -> api.NumberOfActionsRequest
	7,  // 8: api.ChainService.TotalTransferredTokens:input_type -> api.TotalTransferredTokensRequest
	9,  // 9: api.ChainService.BlockSizeByHeight:input_type -> api.BlockSizeByHeightRequest
	11, // 10: api.ChainService.GetLatestBlockHeight:input_type -> api.GetLatestBlockHeightRequest
	14, // 11: api.ChainService.GetBlocks:input_type -> api.GetBlocksRequest
	16, // 12: api.ChainService.GetBlockByHeight:input_type -> api.GetBlockByHeightRequest
	18, // 13: api.ChainService.GetBlockInfoByActionHash:input_type -> api.GetBlockInfoByActionHashRequest
	21, // 14: api.ChainService.GetBlockReceiptByActionHash:input_type -> api.GetBlockReceiptByActionHashRequest
	2,  // 15: api.ChainService.Chain:output_type -> api.ChainResponse
	4,  // 16: api.ChainService.MostRecentTPS:output_type -> api.MostRecentTPSResponse
	6,  // 17: api.ChainService.NumberOfActions:output_type -> api.NumberOfActionsResponse
	8,  // 18: api.ChainService.TotalTransferredTokens:output_type -> api.TotalTransferredTokensResponse
	10, // 19: api.ChainService.BlockSizeByHeight:output_type -> api.BlockSizeByHeightResponse
	12, // 20: api.ChainService.GetLatestBlockHeight:output_type -> api.GetLatestBlockHeightResponse
	15, // 21: api.ChainService.GetBlocks:output_type -> api.GetBlocksResponse
	17, // 22: api.ChainService.GetBlockByHeight:output_type -> api.GetBlockByHeightResponse
	19, // 23: api.ChainService.GetBlockInfoByActionHash:output_type -> api.GetBlockInfoByActionHashResponse
	22, // 24: api.ChainService.GetBlockReceiptByActionHash:output_type -> api.GetBlockReceiptByActionHashResponse
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_chain_proto_init() }
func file_api_chain_proto_init() {
	if File_api_chain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_chain_proto_rawDesc), len(file_api_chain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_chain_proto_goTypes,
		DependencyIndexes: file_api_chain_proto_depIdxs,
		MessageInfos:      file_api_chain_proto_msgTypes,
	}.Build()
	File_api_chain_proto = out.File
	file_api_chain_proto_goTypes = nil
	file_api_chain_proto_depIdxs = nil
}
