// Code generated by proroc-gen-graphql, DO NOT EDIT.
package api

import (
	"context"

	"github.com/graphql-go/graphql"
	"github.com/pkg/errors"
	"github.com/ysugimoto/grpc-graphql-gateway/runtime"
	"google.golang.org/grpc"
)

var (
	gql__type_VotingResultMeta  *graphql.Object      // message VotingResultMeta in api_chain.proto
	gql__type_ChainResponse     *graphql.Object      // message ChainResponse in api_chain.proto
	gql__input_VotingResultMeta *graphql.InputObject // message VotingResultMeta in api_chain.proto
	gql__input_ChainResponse    *graphql.InputObject // message ChainResponse in api_chain.proto
)

func Gql__type_VotingResultMeta() *graphql.Object {
	if gql__type_VotingResultMeta == nil {
		gql__type_VotingResultMeta = graphql.NewObject(graphql.ObjectConfig{
			Name: "Api_Type_VotingResultMeta",
			Fields: graphql.Fields{
				"totalCandidates": &graphql.Field{
					Type: graphql.Int,
				},
				"totalWeightedVotes": &graphql.Field{
					Type: graphql.String,
				},
				"votedTokens": &graphql.Field{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__type_VotingResultMeta
}

func Gql__type_ChainResponse() *graphql.Object {
	if gql__type_ChainResponse == nil {
		gql__type_ChainResponse = graphql.NewObject(graphql.ObjectConfig{
			Name: "Api_Type_ChainResponse",
			Fields: graphql.Fields{
				"mostRecentEpoch": &graphql.Field{
					Type: graphql.Int,
				},
				"mostRecentBlockHeight": &graphql.Field{
					Type: graphql.Int,
				},
				"totalSupply": &graphql.Field{
					Type: graphql.String,
				},
				"totalCirculatingSupply": &graphql.Field{
					Type: graphql.String,
				},
				"totalCirculatingSupplyNoRewardPool": &graphql.Field{
					Type: graphql.String,
				},
				"votingResultMeta": &graphql.Field{
					Type: Gql__type_VotingResultMeta(),
				},
			},
		})
	}
	return gql__type_ChainResponse
}

func Gql__input_VotingResultMeta() *graphql.InputObject {
	if gql__input_VotingResultMeta == nil {
		gql__input_VotingResultMeta = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Api_Input_VotingResultMeta",
			Fields: graphql.InputObjectConfigFieldMap{
				"totalCandidates": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"totalWeightedVotes": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"votedTokens": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__input_VotingResultMeta
}

func Gql__input_ChainResponse() *graphql.InputObject {
	if gql__input_ChainResponse == nil {
		gql__input_ChainResponse = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Api_Input_ChainResponse",
			Fields: graphql.InputObjectConfigFieldMap{
				"mostRecentEpoch": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"mostRecentBlockHeight": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"totalSupply": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"totalCirculatingSupply": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"totalCirculatingSupplyNoRewardPool": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"votingResultMeta": &graphql.InputObjectFieldConfig{
					Type: Gql__input_VotingResultMeta(),
				},
			},
		})
	}
	return gql__input_ChainResponse
}

// graphql__resolver_ChainService is a struct for making query, mutation and resolve fields.
// This struct must be implemented runtime.SchemaBuilder interface.
type graphql__resolver_ChainService struct {

	// Automatic connection host
	host string

	// grpc dial options
	dialOptions []grpc.DialOption

	// grpc client connection.
	// this connection may be provided by user
	conn *grpc.ClientConn
}

// new_graphql_resolver_ChainService creates pointer of service struct
func new_graphql_resolver_ChainService(conn *grpc.ClientConn) *graphql__resolver_ChainService {
	return &graphql__resolver_ChainService{
		conn:        conn,
		host:        "localhost:50051",
		dialOptions: []grpc.DialOption{},
	}
}

// CreateConnection() returns grpc connection which user specified or newly connected and closing function
func (x *graphql__resolver_ChainService) CreateConnection(ctx context.Context) (*grpc.ClientConn, func(), error) {
	// If x.conn is not nil, user injected their own connection
	if x.conn != nil {
		return x.conn, func() {}, nil
	}

	// Otherwise, this handler opens connection with specified host
	conn, err := grpc.DialContext(ctx, x.host, x.dialOptions...)
	if err != nil {
		return nil, nil, err
	}
	return conn, func() { conn.Close() }, nil
}

// GetQueries returns acceptable graphql.Fields for Query.
func (x *graphql__resolver_ChainService) GetQueries(conn *grpc.ClientConn) graphql.Fields {
	return graphql.Fields{
		"Chain": &graphql.Field{
			Type: Gql__type_ChainResponse(),
			Args: graphql.FieldConfigArgument{},
			Resolve: func(p graphql.ResolveParams) (interface{}, error) {
				var req ChainRequest
				if err := runtime.MarshalRequest(p.Args, &req, false); err != nil {
					return nil, errors.Wrap(err, "Failed to marshal request for Chain")
				}
				client := NewChainServiceClient(conn)
				resp, err := client.Chain(p.Context, &req)
				if err != nil {
					return nil, errors.Wrap(err, "Failed to call RPC Chain")
				}
				return resp, nil
			},
		},
	}
}

// GetMutations returns acceptable graphql.Fields for Mutation.
func (x *graphql__resolver_ChainService) GetMutations(conn *grpc.ClientConn) graphql.Fields {
	return graphql.Fields{}
}

// Register package divided graphql handler "without" *grpc.ClientConn,
// therefore gRPC connection will be opened and closed automatically.
// Occasionally you may worry about open/close performance for each handling graphql request,
// then you can call RegisterChainServiceGraphqlHandler with *grpc.ClientConn manually.
func RegisterChainServiceGraphql(mux *runtime.ServeMux) error {
	return RegisterChainServiceGraphqlHandler(mux, nil)
}

// Register package divided graphql handler "with" *grpc.ClientConn.
// this function accepts your defined grpc connection, so that we reuse that and never close connection inside.
// You need to close it maunally when application will terminate.
// Otherwise, you can specify automatic opening connection with ServiceOption directive:
//
// service ChainService {
//    option (graphql.service) = {
//        host: "host:port"
//        insecure: true or false
//    };
//
//    ...with RPC definitions
// }
func RegisterChainServiceGraphqlHandler(mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return mux.AddHandler(new_graphql_resolver_ChainService(conn))
}
