// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: api_voter_reward.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VoterRewardService_VoterRewardsByVoter_FullMethodName    = "/api.VoterRewardService/VoterRewardsByVoter"
	VoterRewardService_VoterRewardsByDelegate_FullMethodName = "/api.VoterRewardService/VoterRewardsByDelegate"
	VoterRewardService_VoterRewardEra_FullMethodName         = "/api.VoterRewardService/VoterRewardEra"
	VoterRewardService_DelegateRewardConfig_FullMethodName   = "/api.VoterRewardService/DelegateRewardConfig"
	VoterRewardService_VoterRewardDestination_FullMethodName = "/api.VoterRewardService/VoterRewardDestination"
	VoterRewardService_UnifiedVoterRewards_FullMethodName    = "/api.VoterRewardService/UnifiedVoterRewards"
	VoterRewardService_DelegateRewardStatus_FullMethodName   = "/api.VoterRewardService/DelegateRewardStatus"
)

// VoterRewardServiceClient is the client API for VoterRewardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoterRewardServiceClient interface {
	// VoterRewardsByVoter lists the on-chain payouts a voter received.
	VoterRewardsByVoter(ctx context.Context, in *VoterRewardsByVoterRequest, opts ...grpc.CallOption) (*VoterRewardsByVoterResponse, error)
	// VoterRewardsByDelegate lists the on-chain payouts a delegate made.
	VoterRewardsByDelegate(ctx context.Context, in *VoterRewardsByDelegateRequest, opts ...grpc.CallOption) (*VoterRewardsByDelegateResponse, error)
	// VoterRewardEra describes one settlement, including its live drain progress.
	VoterRewardEra(ctx context.Context, in *VoterRewardEraRequest, opts ...grpc.CallOption) (*VoterRewardEraResponse, error)
	// DelegateRewardConfig reports opt-in state and frozen commission per delegate.
	DelegateRewardConfig(ctx context.Context, in *DelegateRewardConfigRequest, opts ...grpc.CallOption) (*DelegateRewardConfigResponse, error)
	// VoterRewardDestination reports where a voter's direct payouts are sent.
	VoterRewardDestination(ctx context.Context, in *VoterRewardDestinationRequest, opts ...grpc.CallOption) (*VoterRewardDestinationResponse, error)
	// UnifiedVoterRewards merges the on-chain and Hermes pipelines behind one
	// shape. Callers should prefer it over branching on a delegate's opt-in
	// state themselves — that branch would otherwise be written once in the
	// explorer and once in the wallet, and be wrong in both during migration.
	UnifiedVoterRewards(ctx context.Context, in *UnifiedVoterRewardsRequest, opts ...grpc.CallOption) (*UnifiedVoterRewardsResponse, error)
	// DelegateRewardStatus returns live reward routing per delegate. Prefer it
	// over reading DelegateRewardConfig's newest era, which is a settled
	// historical record and not current state.
	DelegateRewardStatus(ctx context.Context, in *DelegateRewardStatusRequest, opts ...grpc.CallOption) (*DelegateRewardStatusResponse, error)
}

type voterRewardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoterRewardServiceClient(cc grpc.ClientConnInterface) VoterRewardServiceClient {
	return &voterRewardServiceClient{cc}
}

func (c *voterRewardServiceClient) VoterRewardsByVoter(ctx context.Context, in *VoterRewardsByVoterRequest, opts ...grpc.CallOption) (*VoterRewardsByVoterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoterRewardsByVoterResponse)
	err := c.cc.Invoke(ctx, VoterRewardService_VoterRewardsByVoter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voterRewardServiceClient) VoterRewardsByDelegate(ctx context.Context, in *VoterRewardsByDelegateRequest, opts ...grpc.CallOption) (*VoterRewardsByDelegateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoterRewardsByDelegateResponse)
	err := c.cc.Invoke(ctx, VoterRewardService_VoterRewardsByDelegate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voterRewardServiceClient) VoterRewardEra(ctx context.Context, in *VoterRewardEraRequest, opts ...grpc.CallOption) (*VoterRewardEraResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoterRewardEraResponse)
	err := c.cc.Invoke(ctx, VoterRewardService_VoterRewardEra_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voterRewardServiceClient) DelegateRewardConfig(ctx context.Context, in *DelegateRewardConfigRequest, opts ...grpc.CallOption) (*DelegateRewardConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelegateRewardConfigResponse)
	err := c.cc.Invoke(ctx, VoterRewardService_DelegateRewardConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voterRewardServiceClient) VoterRewardDestination(ctx context.Context, in *VoterRewardDestinationRequest, opts ...grpc.CallOption) (*VoterRewardDestinationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoterRewardDestinationResponse)
	err := c.cc.Invoke(ctx, VoterRewardService_VoterRewardDestination_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voterRewardServiceClient) UnifiedVoterRewards(ctx context.Context, in *UnifiedVoterRewardsRequest, opts ...grpc.CallOption) (*UnifiedVoterRewardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnifiedVoterRewardsResponse)
	err := c.cc.Invoke(ctx, VoterRewardService_UnifiedVoterRewards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voterRewardServiceClient) DelegateRewardStatus(ctx context.Context, in *DelegateRewardStatusRequest, opts ...grpc.CallOption) (*DelegateRewardStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelegateRewardStatusResponse)
	err := c.cc.Invoke(ctx, VoterRewardService_DelegateRewardStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoterRewardServiceServer is the server API for VoterRewardService service.
// All implementations must embed UnimplementedVoterRewardServiceServer
// for forward compatibility.
type VoterRewardServiceServer interface {
	// VoterRewardsByVoter lists the on-chain payouts a voter received.
	VoterRewardsByVoter(context.Context, *VoterRewardsByVoterRequest) (*VoterRewardsByVoterResponse, error)
	// VoterRewardsByDelegate lists the on-chain payouts a delegate made.
	VoterRewardsByDelegate(context.Context, *VoterRewardsByDelegateRequest) (*VoterRewardsByDelegateResponse, error)
	// VoterRewardEra describes one settlement, including its live drain progress.
	VoterRewardEra(context.Context, *VoterRewardEraRequest) (*VoterRewardEraResponse, error)
	// DelegateRewardConfig reports opt-in state and frozen commission per delegate.
	DelegateRewardConfig(context.Context, *DelegateRewardConfigRequest) (*DelegateRewardConfigResponse, error)
	// VoterRewardDestination reports where a voter's direct payouts are sent.
	VoterRewardDestination(context.Context, *VoterRewardDestinationRequest) (*VoterRewardDestinationResponse, error)
	// UnifiedVoterRewards merges the on-chain and Hermes pipelines behind one
	// shape. Callers should prefer it over branching on a delegate's opt-in
	// state themselves — that branch would otherwise be written once in the
	// explorer and once in the wallet, and be wrong in both during migration.
	UnifiedVoterRewards(context.Context, *UnifiedVoterRewardsRequest) (*UnifiedVoterRewardsResponse, error)
	// DelegateRewardStatus returns live reward routing per delegate. Prefer it
	// over reading DelegateRewardConfig's newest era, which is a settled
	// historical record and not current state.
	DelegateRewardStatus(context.Context, *DelegateRewardStatusRequest) (*DelegateRewardStatusResponse, error)
	mustEmbedUnimplementedVoterRewardServiceServer()
}

// UnimplementedVoterRewardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoterRewardServiceServer struct{}

func (UnimplementedVoterRewardServiceServer) VoterRewardsByVoter(context.Context, *VoterRewardsByVoterRequest) (*VoterRewardsByVoterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VoterRewardsByVoter not implemented")
}
func (UnimplementedVoterRewardServiceServer) VoterRewardsByDelegate(context.Context, *VoterRewardsByDelegateRequest) (*VoterRewardsByDelegateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VoterRewardsByDelegate not implemented")
}
func (UnimplementedVoterRewardServiceServer) VoterRewardEra(context.Context, *VoterRewardEraRequest) (*VoterRewardEraResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VoterRewardEra not implemented")
}
func (UnimplementedVoterRewardServiceServer) DelegateRewardConfig(context.Context, *DelegateRewardConfigRequest) (*DelegateRewardConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DelegateRewardConfig not implemented")
}
func (UnimplementedVoterRewardServiceServer) VoterRewardDestination(context.Context, *VoterRewardDestinationRequest) (*VoterRewardDestinationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VoterRewardDestination not implemented")
}
func (UnimplementedVoterRewardServiceServer) UnifiedVoterRewards(context.Context, *UnifiedVoterRewardsRequest) (*UnifiedVoterRewardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnifiedVoterRewards not implemented")
}
func (UnimplementedVoterRewardServiceServer) DelegateRewardStatus(context.Context, *DelegateRewardStatusRequest) (*DelegateRewardStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DelegateRewardStatus not implemented")
}
func (UnimplementedVoterRewardServiceServer) mustEmbedUnimplementedVoterRewardServiceServer() {}
func (UnimplementedVoterRewardServiceServer) testEmbeddedByValue()                            {}

// UnsafeVoterRewardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoterRewardServiceServer will
// result in compilation errors.
type UnsafeVoterRewardServiceServer interface {
	mustEmbedUnimplementedVoterRewardServiceServer()
}

func RegisterVoterRewardServiceServer(s grpc.ServiceRegistrar, srv VoterRewardServiceServer) {
	// If the following call panics, it indicates UnimplementedVoterRewardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VoterRewardService_ServiceDesc, srv)
}

func _VoterRewardService_VoterRewardsByVoter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoterRewardsByVoterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoterRewardServiceServer).VoterRewardsByVoter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoterRewardService_VoterRewardsByVoter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoterRewardServiceServer).VoterRewardsByVoter(ctx, req.(*VoterRewardsByVoterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoterRewardService_VoterRewardsByDelegate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoterRewardsByDelegateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoterRewardServiceServer).VoterRewardsByDelegate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoterRewardService_VoterRewardsByDelegate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoterRewardServiceServer).VoterRewardsByDelegate(ctx, req.(*VoterRewardsByDelegateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoterRewardService_VoterRewardEra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoterRewardEraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoterRewardServiceServer).VoterRewardEra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoterRewardService_VoterRewardEra_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoterRewardServiceServer).VoterRewardEra(ctx, req.(*VoterRewardEraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoterRewardService_DelegateRewardConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelegateRewardConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoterRewardServiceServer).DelegateRewardConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoterRewardService_DelegateRewardConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoterRewardServiceServer).DelegateRewardConfig(ctx, req.(*DelegateRewardConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoterRewardService_VoterRewardDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoterRewardDestinationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoterRewardServiceServer).VoterRewardDestination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoterRewardService_VoterRewardDestination_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoterRewardServiceServer).VoterRewardDestination(ctx, req.(*VoterRewardDestinationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoterRewardService_UnifiedVoterRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnifiedVoterRewardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoterRewardServiceServer).UnifiedVoterRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoterRewardService_UnifiedVoterRewards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoterRewardServiceServer).UnifiedVoterRewards(ctx, req.(*UnifiedVoterRewardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoterRewardService_DelegateRewardStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelegateRewardStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoterRewardServiceServer).DelegateRewardStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoterRewardService_DelegateRewardStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoterRewardServiceServer).DelegateRewardStatus(ctx, req.(*DelegateRewardStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VoterRewardService_ServiceDesc is the grpc.ServiceDesc for VoterRewardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoterRewardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.VoterRewardService",
	HandlerType: (*VoterRewardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VoterRewardsByVoter",
			Handler:    _VoterRewardService_VoterRewardsByVoter_Handler,
		},
		{
			MethodName: "VoterRewardsByDelegate",
			Handler:    _VoterRewardService_VoterRewardsByDelegate_Handler,
		},
		{
			MethodName: "VoterRewardEra",
			Handler:    _VoterRewardService_VoterRewardEra_Handler,
		},
		{
			MethodName: "DelegateRewardConfig",
			Handler:    _VoterRewardService_DelegateRewardConfig_Handler,
		},
		{
			MethodName: "VoterRewardDestination",
			Handler:    _VoterRewardService_VoterRewardDestination_Handler,
		},
		{
			MethodName: "UnifiedVoterRewards",
			Handler:    _VoterRewardService_UnifiedVoterRewards_Handler,
		},
		{
			MethodName: "DelegateRewardStatus",
			Handler:    _VoterRewardService_DelegateRewardStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api_voter_reward.proto",
}
