// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: api_account.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AccountService_IotexBalanceByHeight_FullMethodName          = "/api.AccountService/IotexBalanceByHeight"
	AccountService_Erc20TokenBalanceByHeight_FullMethodName     = "/api.AccountService/Erc20TokenBalanceByHeight"
	AccountService_ActiveAccounts_FullMethodName                = "/api.AccountService/ActiveAccounts"
	AccountService_OperatorAddress_FullMethodName               = "/api.AccountService/OperatorAddress"
	AccountService_Alias_FullMethodName                         = "/api.AccountService/Alias"
	AccountService_TotalNumberOfHolders_FullMethodName          = "/api.AccountService/TotalNumberOfHolders"
	AccountService_TotalAccountSupply_FullMethodName            = "/api.AccountService/TotalAccountSupply"
	AccountService_ContractInfo_FullMethodName                  = "/api.AccountService/ContractInfo"
	AccountService_GetAccountMeta_FullMethodName                = "/api.AccountService/GetAccountMeta"
	AccountService_GetContractCreateInfo_FullMethodName         = "/api.AccountService/GetContractCreateInfo"
	AccountService_GetAddressNFTBalances_FullMethodName         = "/api.AccountService/GetAddressNFTBalances"
	AccountService_GetAddressTokenBalances_FullMethodName       = "/api.AccountService/GetAddressTokenBalances"
	AccountService_GetTopAccounts_FullMethodName                = "/api.AccountService/GetTopAccounts"
	AccountService_GetTopAccountsByBalance_FullMethodName       = "/api.AccountService/GetTopAccountsByBalance"
	AccountService_GetAuthorizationsByAuthority_FullMethodName  = "/api.AccountService/GetAuthorizationsByAuthority"
	AccountService_GetAddressTokenBalancesDetail_FullMethodName = "/api.AccountService/GetAddressTokenBalancesDetail"
	AccountService_GetContractsDeployedByAddress_FullMethodName = "/api.AccountService/GetContractsDeployedByAddress"
	AccountService_GetContractByteCode_FullMethodName           = "/api.AccountService/GetContractByteCode"
	AccountService_GetHoldersHistory_FullMethodName             = "/api.AccountService/GetHoldersHistory"
)

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountServiceClient interface {
	// IotexBalanceByHeight returns the balance of the given address at the given height.
	IotexBalanceByHeight(ctx context.Context, in *IotexBalanceByHeightRequest, opts ...grpc.CallOption) (*IotexBalanceByHeightResponse, error)
	Erc20TokenBalanceByHeight(ctx context.Context, in *Erc20TokenBalanceByHeightRequest, opts ...grpc.CallOption) (*Erc20TokenBalanceByHeightResponse, error)
	// ActiveAccounts lists most recently active accounts
	ActiveAccounts(ctx context.Context, in *ActiveAccountsRequest, opts ...grpc.CallOption) (*ActiveAccountsResponse, error)
	// OperatorAddress finds the delegate's operator address given the delegate's alias name
	OperatorAddress(ctx context.Context, in *OperatorAddressRequest, opts ...grpc.CallOption) (*OperatorAddressResponse, error)
	// Alias finds the delegate's alias name given the delegate's operator address
	Alias(ctx context.Context, in *AliasRequest, opts ...grpc.CallOption) (*AliasResponse, error)
	// TotalNumberOfHolders returns total number of IOTX holders so far
	TotalNumberOfHolders(ctx context.Context, in *TotalNumberOfHoldersRequest, opts ...grpc.CallOption) (*TotalNumberOfHoldersResponse, error)
	// TotalAccountSupply returns total amount of tokens held by IoTeX accounts
	TotalAccountSupply(ctx context.Context, in *TotalAccountSupplyRequest, opts ...grpc.CallOption) (*TotalAccountSupplyResponse, error)
	// ContractInfo returns contract info by address, include contract creator, contract create time, contract call times, accumulated transaction fee
	ContractInfo(ctx context.Context, in *ContractInfoRequest, opts ...grpc.CallOption) (*ContractInfoResponse, error)
	// GetAccountMeta returns account metadata (is_contract, block_height, bytecode hash)
	GetAccountMeta(ctx context.Context, in *GetAccountMetaRequest, opts ...grpc.CallOption) (*GetAccountMetaResponse, error)
	// GetContractCreateInfo returns the action hash and creator for a contract
	GetContractCreateInfo(ctx context.Context, in *GetContractCreateInfoRequest, opts ...grpc.CallOption) (*GetContractCreateInfoResponse, error)
	// GetAddressNFTBalances returns NFT token balances for an address
	GetAddressNFTBalances(ctx context.Context, in *GetAddressNFTBalancesRequest, opts ...grpc.CallOption) (*GetAddressNFTBalancesResponse, error)
	// GetAddressTokenBalances returns ERC20 token balances for an address
	GetAddressTokenBalances(ctx context.Context, in *GetAddressTokenBalancesRequest, opts ...grpc.CallOption) (*GetAddressTokenBalancesResponse, error)
	// GetTopAccounts returns top stakers from stats_top_list_view with filters
	GetTopAccounts(ctx context.Context, in *GetTopAccountsRequest, opts ...grpc.CallOption) (*GetTopAccountsResponse, error)
	// GetTopAccountsByBalance returns top accounts by IOTX balance from account_income_count
	GetTopAccountsByBalance(ctx context.Context, in *GetTopAccountsByBalanceRequest, opts ...grpc.CallOption) (*GetTopAccountsByBalanceResponse, error)
	// GetAuthorizationsByAuthority returns EIP-7702 authorization history for an authority address
	GetAuthorizationsByAuthority(ctx context.Context, in *GetAuthorizationsByAuthorityRequest, opts ...grpc.CallOption) (*GetAuthorizationsByAuthorityResponse, error)
	// GetAddressTokenBalancesDetail returns ERC20 balances with name/symbol/decimals/price
	GetAddressTokenBalancesDetail(ctx context.Context, in *GetAddressTokenBalancesDetailRequest, opts ...grpc.CallOption) (*GetAddressTokenBalancesDetailResponse, error)
	// GetContractsDeployedByAddress lists contracts deployed by a given address
	GetContractsDeployedByAddress(ctx context.Context, in *GetContractsDeployedByAddressRequest, opts ...grpc.CallOption) (*GetContractsDeployedByAddressResponse, error)
	// GetContractByteCode returns the raw bytecode (hex) of a contract
	GetContractByteCode(ctx context.Context, in *GetContractByteCodeRequest, opts ...grpc.CallOption) (*GetContractByteCodeResponse, error)
	// GetHoldersHistory returns daily holder counts over a date range
	GetHoldersHistory(ctx context.Context, in *GetHoldersHistoryRequest, opts ...grpc.CallOption) (*GetHoldersHistoryResponse, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) IotexBalanceByHeight(ctx context.Context, in *IotexBalanceByHeightRequest, opts ...grpc.CallOption) (*IotexBalanceByHeightResponse, error) {
	out := new(IotexBalanceByHeightResponse)
	err := c.cc.Invoke(ctx, AccountService_IotexBalanceByHeight_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Erc20TokenBalanceByHeight(ctx context.Context, in *Erc20TokenBalanceByHeightRequest, opts ...grpc.CallOption) (*Erc20TokenBalanceByHeightResponse, error) {
	out := new(Erc20TokenBalanceByHeightResponse)
	err := c.cc.Invoke(ctx, AccountService_Erc20TokenBalanceByHeight_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ActiveAccounts(ctx context.Context, in *ActiveAccountsRequest, opts ...grpc.CallOption) (*ActiveAccountsResponse, error) {
	out := new(ActiveAccountsResponse)
	err := c.cc.Invoke(ctx, AccountService_ActiveAccounts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) OperatorAddress(ctx context.Context, in *OperatorAddressRequest, opts ...grpc.CallOption) (*OperatorAddressResponse, error) {
	out := new(OperatorAddressResponse)
	err := c.cc.Invoke(ctx, AccountService_OperatorAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Alias(ctx context.Context, in *AliasRequest, opts ...grpc.CallOption) (*AliasResponse, error) {
	out := new(AliasResponse)
	err := c.cc.Invoke(ctx, AccountService_Alias_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) TotalNumberOfHolders(ctx context.Context, in *TotalNumberOfHoldersRequest, opts ...grpc.CallOption) (*TotalNumberOfHoldersResponse, error) {
	out := new(TotalNumberOfHoldersResponse)
	err := c.cc.Invoke(ctx, AccountService_TotalNumberOfHolders_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) TotalAccountSupply(ctx context.Context, in *TotalAccountSupplyRequest, opts ...grpc.CallOption) (*TotalAccountSupplyResponse, error) {
	out := new(TotalAccountSupplyResponse)
	err := c.cc.Invoke(ctx, AccountService_TotalAccountSupply_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ContractInfo(ctx context.Context, in *ContractInfoRequest, opts ...grpc.CallOption) (*ContractInfoResponse, error) {
	out := new(ContractInfoResponse)
	err := c.cc.Invoke(ctx, AccountService_ContractInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccountMeta(ctx context.Context, in *GetAccountMetaRequest, opts ...grpc.CallOption) (*GetAccountMetaResponse, error) {
	out := new(GetAccountMetaResponse)
	err := c.cc.Invoke(ctx, AccountService_GetAccountMeta_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetContractCreateInfo(ctx context.Context, in *GetContractCreateInfoRequest, opts ...grpc.CallOption) (*GetContractCreateInfoResponse, error) {
	out := new(GetContractCreateInfoResponse)
	err := c.cc.Invoke(ctx, AccountService_GetContractCreateInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAddressNFTBalances(ctx context.Context, in *GetAddressNFTBalancesRequest, opts ...grpc.CallOption) (*GetAddressNFTBalancesResponse, error) {
	out := new(GetAddressNFTBalancesResponse)
	err := c.cc.Invoke(ctx, AccountService_GetAddressNFTBalances_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAddressTokenBalances(ctx context.Context, in *GetAddressTokenBalancesRequest, opts ...grpc.CallOption) (*GetAddressTokenBalancesResponse, error) {
	out := new(GetAddressTokenBalancesResponse)
	err := c.cc.Invoke(ctx, AccountService_GetAddressTokenBalances_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetTopAccounts(ctx context.Context, in *GetTopAccountsRequest, opts ...grpc.CallOption) (*GetTopAccountsResponse, error) {
	out := new(GetTopAccountsResponse)
	err := c.cc.Invoke(ctx, AccountService_GetTopAccounts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetTopAccountsByBalance(ctx context.Context, in *GetTopAccountsByBalanceRequest, opts ...grpc.CallOption) (*GetTopAccountsByBalanceResponse, error) {
	out := new(GetTopAccountsByBalanceResponse)
	err := c.cc.Invoke(ctx, AccountService_GetTopAccountsByBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAuthorizationsByAuthority(ctx context.Context, in *GetAuthorizationsByAuthorityRequest, opts ...grpc.CallOption) (*GetAuthorizationsByAuthorityResponse, error) {
	out := new(GetAuthorizationsByAuthorityResponse)
	err := c.cc.Invoke(ctx, AccountService_GetAuthorizationsByAuthority_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAddressTokenBalancesDetail(ctx context.Context, in *GetAddressTokenBalancesDetailRequest, opts ...grpc.CallOption) (*GetAddressTokenBalancesDetailResponse, error) {
	out := new(GetAddressTokenBalancesDetailResponse)
	err := c.cc.Invoke(ctx, AccountService_GetAddressTokenBalancesDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetContractsDeployedByAddress(ctx context.Context, in *GetContractsDeployedByAddressRequest, opts ...grpc.CallOption) (*GetContractsDeployedByAddressResponse, error) {
	out := new(GetContractsDeployedByAddressResponse)
	err := c.cc.Invoke(ctx, AccountService_GetContractsDeployedByAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetContractByteCode(ctx context.Context, in *GetContractByteCodeRequest, opts ...grpc.CallOption) (*GetContractByteCodeResponse, error) {
	out := new(GetContractByteCodeResponse)
	err := c.cc.Invoke(ctx, AccountService_GetContractByteCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetHoldersHistory(ctx context.Context, in *GetHoldersHistoryRequest, opts ...grpc.CallOption) (*GetHoldersHistoryResponse, error) {
	out := new(GetHoldersHistoryResponse)
	err := c.cc.Invoke(ctx, AccountService_GetHoldersHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
// All implementations must embed UnimplementedAccountServiceServer
// for forward compatibility
type AccountServiceServer interface {
	// IotexBalanceByHeight returns the balance of the given address at the given height.
	IotexBalanceByHeight(context.Context, *IotexBalanceByHeightRequest) (*IotexBalanceByHeightResponse, error)
	Erc20TokenBalanceByHeight(context.Context, *Erc20TokenBalanceByHeightRequest) (*Erc20TokenBalanceByHeightResponse, error)
	// ActiveAccounts lists most recently active accounts
	ActiveAccounts(context.Context, *ActiveAccountsRequest) (*ActiveAccountsResponse, error)
	// OperatorAddress finds the delegate's operator address given the delegate's alias name
	OperatorAddress(context.Context, *OperatorAddressRequest) (*OperatorAddressResponse, error)
	// Alias finds the delegate's alias name given the delegate's operator address
	Alias(context.Context, *AliasRequest) (*AliasResponse, error)
	// TotalNumberOfHolders returns total number of IOTX holders so far
	TotalNumberOfHolders(context.Context, *TotalNumberOfHoldersRequest) (*TotalNumberOfHoldersResponse, error)
	// TotalAccountSupply returns total amount of tokens held by IoTeX accounts
	TotalAccountSupply(context.Context, *TotalAccountSupplyRequest) (*TotalAccountSupplyResponse, error)
	// ContractInfo returns contract info by address, include contract creator, contract create time, contract call times, accumulated transaction fee
	ContractInfo(context.Context, *ContractInfoRequest) (*ContractInfoResponse, error)
	// GetAccountMeta returns account metadata (is_contract, block_height, bytecode hash)
	GetAccountMeta(context.Context, *GetAccountMetaRequest) (*GetAccountMetaResponse, error)
	// GetContractCreateInfo returns the action hash and creator for a contract
	GetContractCreateInfo(context.Context, *GetContractCreateInfoRequest) (*GetContractCreateInfoResponse, error)
	// GetAddressNFTBalances returns NFT token balances for an address
	GetAddressNFTBalances(context.Context, *GetAddressNFTBalancesRequest) (*GetAddressNFTBalancesResponse, error)
	// GetAddressTokenBalances returns ERC20 token balances for an address
	GetAddressTokenBalances(context.Context, *GetAddressTokenBalancesRequest) (*GetAddressTokenBalancesResponse, error)
	// GetTopAccounts returns top stakers from stats_top_list_view with filters
	GetTopAccounts(context.Context, *GetTopAccountsRequest) (*GetTopAccountsResponse, error)
	// GetTopAccountsByBalance returns top accounts by IOTX balance from account_income_count
	GetTopAccountsByBalance(context.Context, *GetTopAccountsByBalanceRequest) (*GetTopAccountsByBalanceResponse, error)
	// GetAuthorizationsByAuthority returns EIP-7702 authorization history for an authority address
	GetAuthorizationsByAuthority(context.Context, *GetAuthorizationsByAuthorityRequest) (*GetAuthorizationsByAuthorityResponse, error)
	// GetAddressTokenBalancesDetail returns ERC20 balances with name/symbol/decimals/price
	GetAddressTokenBalancesDetail(context.Context, *GetAddressTokenBalancesDetailRequest) (*GetAddressTokenBalancesDetailResponse, error)
	// GetContractsDeployedByAddress lists contracts deployed by a given address
	GetContractsDeployedByAddress(context.Context, *GetContractsDeployedByAddressRequest) (*GetContractsDeployedByAddressResponse, error)
	// GetContractByteCode returns the raw bytecode (hex) of a contract
	GetContractByteCode(context.Context, *GetContractByteCodeRequest) (*GetContractByteCodeResponse, error)
	// GetHoldersHistory returns daily holder counts over a date range
	GetHoldersHistory(context.Context, *GetHoldersHistoryRequest) (*GetHoldersHistoryResponse, error)
	mustEmbedUnimplementedAccountServiceServer()
}

// UnimplementedAccountServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct {
}

func (UnimplementedAccountServiceServer) IotexBalanceByHeight(context.Context, *IotexBalanceByHeightRequest) (*IotexBalanceByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IotexBalanceByHeight not implemented")
}
func (UnimplementedAccountServiceServer) Erc20TokenBalanceByHeight(context.Context, *Erc20TokenBalanceByHeightRequest) (*Erc20TokenBalanceByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Erc20TokenBalanceByHeight not implemented")
}
func (UnimplementedAccountServiceServer) ActiveAccounts(context.Context, *ActiveAccountsRequest) (*ActiveAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActiveAccounts not implemented")
}
func (UnimplementedAccountServiceServer) OperatorAddress(context.Context, *OperatorAddressRequest) (*OperatorAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OperatorAddress not implemented")
}
func (UnimplementedAccountServiceServer) Alias(context.Context, *AliasRequest) (*AliasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Alias not implemented")
}
func (UnimplementedAccountServiceServer) TotalNumberOfHolders(context.Context, *TotalNumberOfHoldersRequest) (*TotalNumberOfHoldersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TotalNumberOfHolders not implemented")
}
func (UnimplementedAccountServiceServer) TotalAccountSupply(context.Context, *TotalAccountSupplyRequest) (*TotalAccountSupplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TotalAccountSupply not implemented")
}
func (UnimplementedAccountServiceServer) ContractInfo(context.Context, *ContractInfoRequest) (*ContractInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContractInfo not implemented")
}
func (UnimplementedAccountServiceServer) GetAccountMeta(context.Context, *GetAccountMetaRequest) (*GetAccountMetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountMeta not implemented")
}
func (UnimplementedAccountServiceServer) GetContractCreateInfo(context.Context, *GetContractCreateInfoRequest) (*GetContractCreateInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContractCreateInfo not implemented")
}
func (UnimplementedAccountServiceServer) GetAddressNFTBalances(context.Context, *GetAddressNFTBalancesRequest) (*GetAddressNFTBalancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressNFTBalances not implemented")
}
func (UnimplementedAccountServiceServer) GetAddressTokenBalances(context.Context, *GetAddressTokenBalancesRequest) (*GetAddressTokenBalancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressTokenBalances not implemented")
}
func (UnimplementedAccountServiceServer) GetTopAccounts(context.Context, *GetTopAccountsRequest) (*GetTopAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopAccounts not implemented")
}
func (UnimplementedAccountServiceServer) GetTopAccountsByBalance(context.Context, *GetTopAccountsByBalanceRequest) (*GetTopAccountsByBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopAccountsByBalance not implemented")
}
func (UnimplementedAccountServiceServer) GetAuthorizationsByAuthority(context.Context, *GetAuthorizationsByAuthorityRequest) (*GetAuthorizationsByAuthorityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthorizationsByAuthority not implemented")
}
func (UnimplementedAccountServiceServer) GetAddressTokenBalancesDetail(context.Context, *GetAddressTokenBalancesDetailRequest) (*GetAddressTokenBalancesDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressTokenBalancesDetail not implemented")
}
func (UnimplementedAccountServiceServer) GetContractsDeployedByAddress(context.Context, *GetContractsDeployedByAddressRequest) (*GetContractsDeployedByAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContractsDeployedByAddress not implemented")
}
func (UnimplementedAccountServiceServer) GetContractByteCode(context.Context, *GetContractByteCodeRequest) (*GetContractByteCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContractByteCode not implemented")
}
func (UnimplementedAccountServiceServer) GetHoldersHistory(context.Context, *GetHoldersHistoryRequest) (*GetHoldersHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHoldersHistory not implemented")
}
func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceServer will
// result in compilation errors.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_IotexBalanceByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IotexBalanceByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).IotexBalanceByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_IotexBalanceByHeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).IotexBalanceByHeight(ctx, req.(*IotexBalanceByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Erc20TokenBalanceByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Erc20TokenBalanceByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Erc20TokenBalanceByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_Erc20TokenBalanceByHeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Erc20TokenBalanceByHeight(ctx, req.(*Erc20TokenBalanceByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ActiveAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActiveAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ActiveAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ActiveAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ActiveAccounts(ctx, req.(*ActiveAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_OperatorAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperatorAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).OperatorAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_OperatorAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).OperatorAddress(ctx, req.(*OperatorAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Alias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Alias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_Alias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Alias(ctx, req.(*AliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_TotalNumberOfHolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TotalNumberOfHoldersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).TotalNumberOfHolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_TotalNumberOfHolders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).TotalNumberOfHolders(ctx, req.(*TotalNumberOfHoldersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_TotalAccountSupply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TotalAccountSupplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).TotalAccountSupply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_TotalAccountSupply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).TotalAccountSupply(ctx, req.(*TotalAccountSupplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ContractInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContractInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ContractInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ContractInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ContractInfo(ctx, req.(*ContractInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAccountMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccountMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetAccountMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccountMeta(ctx, req.(*GetAccountMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetContractCreateInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContractCreateInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetContractCreateInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetContractCreateInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetContractCreateInfo(ctx, req.(*GetContractCreateInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAddressNFTBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressNFTBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAddressNFTBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetAddressNFTBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAddressNFTBalances(ctx, req.(*GetAddressNFTBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAddressTokenBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressTokenBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAddressTokenBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetAddressTokenBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAddressTokenBalances(ctx, req.(*GetAddressTokenBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetTopAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetTopAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetTopAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetTopAccounts(ctx, req.(*GetTopAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetTopAccountsByBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopAccountsByBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetTopAccountsByBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetTopAccountsByBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetTopAccountsByBalance(ctx, req.(*GetTopAccountsByBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAuthorizationsByAuthority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorizationsByAuthorityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAuthorizationsByAuthority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetAuthorizationsByAuthority_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAuthorizationsByAuthority(ctx, req.(*GetAuthorizationsByAuthorityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAddressTokenBalancesDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressTokenBalancesDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAddressTokenBalancesDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetAddressTokenBalancesDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAddressTokenBalancesDetail(ctx, req.(*GetAddressTokenBalancesDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetContractsDeployedByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContractsDeployedByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetContractsDeployedByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetContractsDeployedByAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetContractsDeployedByAddress(ctx, req.(*GetContractsDeployedByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetContractByteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContractByteCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetContractByteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetContractByteCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetContractByteCode(ctx, req.(*GetContractByteCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetHoldersHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHoldersHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetHoldersHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetHoldersHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetHoldersHistory(ctx, req.(*GetHoldersHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IotexBalanceByHeight",
			Handler:    _AccountService_IotexBalanceByHeight_Handler,
		},
		{
			MethodName: "Erc20TokenBalanceByHeight",
			Handler:    _AccountService_Erc20TokenBalanceByHeight_Handler,
		},
		{
			MethodName: "ActiveAccounts",
			Handler:    _AccountService_ActiveAccounts_Handler,
		},
		{
			MethodName: "OperatorAddress",
			Handler:    _AccountService_OperatorAddress_Handler,
		},
		{
			MethodName: "Alias",
			Handler:    _AccountService_Alias_Handler,
		},
		{
			MethodName: "TotalNumberOfHolders",
			Handler:    _AccountService_TotalNumberOfHolders_Handler,
		},
		{
			MethodName: "TotalAccountSupply",
			Handler:    _AccountService_TotalAccountSupply_Handler,
		},
		{
			MethodName: "ContractInfo",
			Handler:    _AccountService_ContractInfo_Handler,
		},
		{
			MethodName: "GetAccountMeta",
			Handler:    _AccountService_GetAccountMeta_Handler,
		},
		{
			MethodName: "GetContractCreateInfo",
			Handler:    _AccountService_GetContractCreateInfo_Handler,
		},
		{
			MethodName: "GetAddressNFTBalances",
			Handler:    _AccountService_GetAddressNFTBalances_Handler,
		},
		{
			MethodName: "GetAddressTokenBalances",
			Handler:    _AccountService_GetAddressTokenBalances_Handler,
		},
		{
			MethodName: "GetTopAccounts",
			Handler:    _AccountService_GetTopAccounts_Handler,
		},
		{
			MethodName: "GetTopAccountsByBalance",
			Handler:    _AccountService_GetTopAccountsByBalance_Handler,
		},
		{
			MethodName: "GetAuthorizationsByAuthority",
			Handler:    _AccountService_GetAuthorizationsByAuthority_Handler,
		},
		{
			MethodName: "GetAddressTokenBalancesDetail",
			Handler:    _AccountService_GetAddressTokenBalancesDetail_Handler,
		},
		{
			MethodName: "GetContractsDeployedByAddress",
			Handler:    _AccountService_GetContractsDeployedByAddress_Handler,
		},
		{
			MethodName: "GetContractByteCode",
			Handler:    _AccountService_GetContractByteCode_Handler,
		},
		{
			MethodName: "GetHoldersHistory",
			Handler:    _AccountService_GetHoldersHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api_account.proto",
}
