// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: api_approval.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ApprovalService_GetXRC20Approvals_FullMethodName  = "/api.ApprovalService/GetXRC20Approvals"
	ApprovalService_GetXRC721Approvals_FullMethodName = "/api.ApprovalService/GetXRC721Approvals"
)

// ApprovalServiceClient is the client API for ApprovalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApprovalServiceClient interface {
	GetXRC20Approvals(ctx context.Context, in *GetXRC20ApprovalsRequest, opts ...grpc.CallOption) (*GetXRC20ApprovalsResponse, error)
	GetXRC721Approvals(ctx context.Context, in *GetXRC721ApprovalsRequest, opts ...grpc.CallOption) (*GetXRC721ApprovalsResponse, error)
}

type approvalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApprovalServiceClient(cc grpc.ClientConnInterface) ApprovalServiceClient {
	return &approvalServiceClient{cc}
}

func (c *approvalServiceClient) GetXRC20Approvals(ctx context.Context, in *GetXRC20ApprovalsRequest, opts ...grpc.CallOption) (*GetXRC20ApprovalsResponse, error) {
	out := new(GetXRC20ApprovalsResponse)
	err := c.cc.Invoke(ctx, ApprovalService_GetXRC20Approvals_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) GetXRC721Approvals(ctx context.Context, in *GetXRC721ApprovalsRequest, opts ...grpc.CallOption) (*GetXRC721ApprovalsResponse, error) {
	out := new(GetXRC721ApprovalsResponse)
	err := c.cc.Invoke(ctx, ApprovalService_GetXRC721Approvals_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApprovalServiceServer is the server API for ApprovalService service.
// All implementations must embed UnimplementedApprovalServiceServer
// for forward compatibility
type ApprovalServiceServer interface {
	GetXRC20Approvals(context.Context, *GetXRC20ApprovalsRequest) (*GetXRC20ApprovalsResponse, error)
	GetXRC721Approvals(context.Context, *GetXRC721ApprovalsRequest) (*GetXRC721ApprovalsResponse, error)
	mustEmbedUnimplementedApprovalServiceServer()
}

// UnimplementedApprovalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedApprovalServiceServer struct {
}

func (UnimplementedApprovalServiceServer) GetXRC20Approvals(context.Context, *GetXRC20ApprovalsRequest) (*GetXRC20ApprovalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetXRC20Approvals not implemented")
}
func (UnimplementedApprovalServiceServer) GetXRC721Approvals(context.Context, *GetXRC721ApprovalsRequest) (*GetXRC721ApprovalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetXRC721Approvals not implemented")
}
func (UnimplementedApprovalServiceServer) mustEmbedUnimplementedApprovalServiceServer() {}

// UnsafeApprovalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApprovalServiceServer will
// result in compilation errors.
type UnsafeApprovalServiceServer interface {
	mustEmbedUnimplementedApprovalServiceServer()
}

func RegisterApprovalServiceServer(s grpc.ServiceRegistrar, srv ApprovalServiceServer) {
	s.RegisterService(&ApprovalService_ServiceDesc, srv)
}

func _ApprovalService_GetXRC20Approvals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetXRC20ApprovalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).GetXRC20Approvals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_GetXRC20Approvals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).GetXRC20Approvals(ctx, req.(*GetXRC20ApprovalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_GetXRC721Approvals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetXRC721ApprovalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).GetXRC721Approvals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_GetXRC721Approvals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).GetXRC721Approvals(ctx, req.(*GetXRC721ApprovalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApprovalService_ServiceDesc is the grpc.ServiceDesc for ApprovalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApprovalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ApprovalService",
	HandlerType: (*ApprovalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetXRC20Approvals",
			Handler:    _ApprovalService_GetXRC20Approvals_Handler,
		},
		{
			MethodName: "GetXRC721Approvals",
			Handler:    _ApprovalService_GetXRC721Approvals_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api_approval.proto",
}
