// Code generated by proroc-gen-graphql, DO NOT EDIT.
package api

import (
	"context"

	"github.com/graphql-go/graphql"
	pagination "github.com/iotexproject/iotex-analyser-api/api/pagination"
	"github.com/pkg/errors"
	"github.com/ysugimoto/grpc-graphql-gateway/runtime"
	"google.golang.org/grpc"
)

var (
	gql__type_Xrc20Action                        *graphql.Object      // message Xrc20Action in api_xrc20.proto
	gql__type_XRC20TokenHolderAddressesResponse  *graphql.Object      // message XRC20TokenHolderAddressesResponse in api_xrc20.proto
	gql__type_XRC20TokenHolderAddressesRequest   *graphql.Object      // message XRC20TokenHolderAddressesRequest in api_xrc20.proto
	gql__type_XRC20ByPageResponse                *graphql.Object      // message XRC20ByPageResponse in api_xrc20.proto
	gql__type_XRC20ByPageRequest                 *graphql.Object      // message XRC20ByPageRequest in api_xrc20.proto
	gql__type_XRC20ByContractAddressResponse     *graphql.Object      // message XRC20ByContractAddressResponse in api_xrc20.proto
	gql__type_XRC20ByContractAddressRequest      *graphql.Object      // message XRC20ByContractAddressRequest in api_xrc20.proto
	gql__type_XRC20ByAddressResponse             *graphql.Object      // message XRC20ByAddressResponse in api_xrc20.proto
	gql__type_XRC20ByAddressRequest              *graphql.Object      // message XRC20ByAddressRequest in api_xrc20.proto
	gql__type_XRC20AddressesResponse             *graphql.Object      // message XRC20AddressesResponse in api_xrc20.proto
	gql__type_XRC20AddressesRequest              *graphql.Object      // message XRC20AddressesRequest in api_xrc20.proto
	gql__input_Xrc20Action                       *graphql.InputObject // message Xrc20Action in api_xrc20.proto
	gql__input_XRC20TokenHolderAddressesResponse *graphql.InputObject // message XRC20TokenHolderAddressesResponse in api_xrc20.proto
	gql__input_XRC20TokenHolderAddressesRequest  *graphql.InputObject // message XRC20TokenHolderAddressesRequest in api_xrc20.proto
	gql__input_XRC20ByPageResponse               *graphql.InputObject // message XRC20ByPageResponse in api_xrc20.proto
	gql__input_XRC20ByPageRequest                *graphql.InputObject // message XRC20ByPageRequest in api_xrc20.proto
	gql__input_XRC20ByContractAddressResponse    *graphql.InputObject // message XRC20ByContractAddressResponse in api_xrc20.proto
	gql__input_XRC20ByContractAddressRequest     *graphql.InputObject // message XRC20ByContractAddressRequest in api_xrc20.proto
	gql__input_XRC20ByAddressResponse            *graphql.InputObject // message XRC20ByAddressResponse in api_xrc20.proto
	gql__input_XRC20ByAddressRequest             *graphql.InputObject // message XRC20ByAddressRequest in api_xrc20.proto
	gql__input_XRC20AddressesResponse            *graphql.InputObject // message XRC20AddressesResponse in api_xrc20.proto
	gql__input_XRC20AddressesRequest             *graphql.InputObject // message XRC20AddressesRequest in api_xrc20.proto
)

func Gql__type_Xrc20Action() *graphql.Object {
	if gql__type_Xrc20Action == nil {
		gql__type_Xrc20Action = graphql.NewObject(graphql.ObjectConfig{
			Name: "Api_Type_Xrc20Action",
			Fields: graphql.Fields{
				"actHash": &graphql.Field{
					Type: graphql.String,
				},
				"sender": &graphql.Field{
					Type: graphql.String,
				},
				"recipient": &graphql.Field{
					Type: graphql.String,
				},
				"amount": &graphql.Field{
					Type: graphql.String,
				},
				"timestamp": &graphql.Field{
					Type: graphql.Int,
				},
				"contract": &graphql.Field{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__type_Xrc20Action
}

func Gql__type_XRC20TokenHolderAddressesResponse() *graphql.Object {
	if gql__type_XRC20TokenHolderAddressesResponse == nil {
		gql__type_XRC20TokenHolderAddressesResponse = graphql.NewObject(graphql.ObjectConfig{
			Name: "Api_Type_XRC20TokenHolderAddressesResponse",
			Fields: graphql.Fields{
				"count": &graphql.Field{
					Type: graphql.Int,
				},
				"addresses": &graphql.Field{
					Type: graphql.NewList(graphql.String),
				},
			},
		})
	}
	return gql__type_XRC20TokenHolderAddressesResponse
}

func Gql__type_XRC20TokenHolderAddressesRequest() *graphql.Object {
	if gql__type_XRC20TokenHolderAddressesRequest == nil {
		gql__type_XRC20TokenHolderAddressesRequest = graphql.NewObject(graphql.ObjectConfig{
			Name: "Api_Type_XRC20TokenHolderAddressesRequest",
			Fields: graphql.Fields{
				"tokenAddress": &graphql.Field{
					Type: graphql.String,
				},
				"pagination": &graphql.Field{
					Type: pagination.Gql__type_Pagination(),
				},
			},
		})
	}
	return gql__type_XRC20TokenHolderAddressesRequest
}

func Gql__type_XRC20ByPageResponse() *graphql.Object {
	if gql__type_XRC20ByPageResponse == nil {
		gql__type_XRC20ByPageResponse = graphql.NewObject(graphql.ObjectConfig{
			Name: "Api_Type_XRC20ByPageResponse",
			Fields: graphql.Fields{
				"exist": &graphql.Field{
					Type: graphql.Boolean,
				},
				"count": &graphql.Field{
					Type: graphql.Int,
				},
				"xrc20": &graphql.Field{
					Type: graphql.NewList(Gql__type_Xrc20Action()),
				},
			},
		})
	}
	return gql__type_XRC20ByPageResponse
}

func Gql__type_XRC20ByPageRequest() *graphql.Object {
	if gql__type_XRC20ByPageRequest == nil {
		gql__type_XRC20ByPageRequest = graphql.NewObject(graphql.ObjectConfig{
			Name: "Api_Type_XRC20ByPageRequest",
			Fields: graphql.Fields{
				"pagination": &graphql.Field{
					Type: pagination.Gql__type_Pagination(),
				},
			},
		})
	}
	return gql__type_XRC20ByPageRequest
}

func Gql__type_XRC20ByContractAddressResponse() *graphql.Object {
	if gql__type_XRC20ByContractAddressResponse == nil {
		gql__type_XRC20ByContractAddressResponse = graphql.NewObject(graphql.ObjectConfig{
			Name: "Api_Type_XRC20ByContractAddressResponse",
			Fields: graphql.Fields{
				"exist": &graphql.Field{
					Type: graphql.Boolean,
				},
				"count": &graphql.Field{
					Type: graphql.Int,
				},
				"xrc20": &graphql.Field{
					Type: graphql.NewList(Gql__type_Xrc20Action()),
				},
			},
		})
	}
	return gql__type_XRC20ByContractAddressResponse
}

func Gql__type_XRC20ByContractAddressRequest() *graphql.Object {
	if gql__type_XRC20ByContractAddressRequest == nil {
		gql__type_XRC20ByContractAddressRequest = graphql.NewObject(graphql.ObjectConfig{
			Name: "Api_Type_XRC20ByContractAddressRequest",
			Fields: graphql.Fields{
				"address": &graphql.Field{
					Type: graphql.String,
				},
				"pagination": &graphql.Field{
					Type: pagination.Gql__type_Pagination(),
				},
			},
		})
	}
	return gql__type_XRC20ByContractAddressRequest
}

func Gql__type_XRC20ByAddressResponse() *graphql.Object {
	if gql__type_XRC20ByAddressResponse == nil {
		gql__type_XRC20ByAddressResponse = graphql.NewObject(graphql.ObjectConfig{
			Name: "Api_Type_XRC20ByAddressResponse",
			Fields: graphql.Fields{
				"exist": &graphql.Field{
					Type: graphql.Boolean,
				},
				"count": &graphql.Field{
					Type: graphql.Int,
				},
				"xrc20": &graphql.Field{
					Type: graphql.NewList(Gql__type_Xrc20Action()),
				},
			},
		})
	}
	return gql__type_XRC20ByAddressResponse
}

func Gql__type_XRC20ByAddressRequest() *graphql.Object {
	if gql__type_XRC20ByAddressRequest == nil {
		gql__type_XRC20ByAddressRequest = graphql.NewObject(graphql.ObjectConfig{
			Name: "Api_Type_XRC20ByAddressRequest",
			Fields: graphql.Fields{
				"address": &graphql.Field{
					Type: graphql.String,
				},
				"pagination": &graphql.Field{
					Type: pagination.Gql__type_Pagination(),
				},
			},
		})
	}
	return gql__type_XRC20ByAddressRequest
}

func Gql__type_XRC20AddressesResponse() *graphql.Object {
	if gql__type_XRC20AddressesResponse == nil {
		gql__type_XRC20AddressesResponse = graphql.NewObject(graphql.ObjectConfig{
			Name: "Api_Type_XRC20AddressesResponse",
			Fields: graphql.Fields{
				"exist": &graphql.Field{
					Type: graphql.Boolean,
				},
				"count": &graphql.Field{
					Type: graphql.Int,
				},
				"addresses": &graphql.Field{
					Type: graphql.NewList(graphql.String),
				},
			},
		})
	}
	return gql__type_XRC20AddressesResponse
}

func Gql__type_XRC20AddressesRequest() *graphql.Object {
	if gql__type_XRC20AddressesRequest == nil {
		gql__type_XRC20AddressesRequest = graphql.NewObject(graphql.ObjectConfig{
			Name: "Api_Type_XRC20AddressesRequest",
			Fields: graphql.Fields{
				"pagination": &graphql.Field{
					Type: pagination.Gql__type_Pagination(),
				},
			},
		})
	}
	return gql__type_XRC20AddressesRequest
}

func Gql__input_Xrc20Action() *graphql.InputObject {
	if gql__input_Xrc20Action == nil {
		gql__input_Xrc20Action = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Api_Input_Xrc20Action",
			Fields: graphql.InputObjectConfigFieldMap{
				"actHash": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"sender": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"recipient": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"amount": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"timestamp": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"contract": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__input_Xrc20Action
}

func Gql__input_XRC20TokenHolderAddressesResponse() *graphql.InputObject {
	if gql__input_XRC20TokenHolderAddressesResponse == nil {
		gql__input_XRC20TokenHolderAddressesResponse = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Api_Input_XRC20TokenHolderAddressesResponse",
			Fields: graphql.InputObjectConfigFieldMap{
				"count": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"addresses": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.String),
				},
			},
		})
	}
	return gql__input_XRC20TokenHolderAddressesResponse
}

func Gql__input_XRC20TokenHolderAddressesRequest() *graphql.InputObject {
	if gql__input_XRC20TokenHolderAddressesRequest == nil {
		gql__input_XRC20TokenHolderAddressesRequest = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Api_Input_XRC20TokenHolderAddressesRequest",
			Fields: graphql.InputObjectConfigFieldMap{
				"tokenAddress": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"pagination": &graphql.InputObjectFieldConfig{
					Type: pagination.Gql__input_Pagination(),
				},
			},
		})
	}
	return gql__input_XRC20TokenHolderAddressesRequest
}

func Gql__input_XRC20ByPageResponse() *graphql.InputObject {
	if gql__input_XRC20ByPageResponse == nil {
		gql__input_XRC20ByPageResponse = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Api_Input_XRC20ByPageResponse",
			Fields: graphql.InputObjectConfigFieldMap{
				"exist": &graphql.InputObjectFieldConfig{
					Type: graphql.Boolean,
				},
				"count": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"xrc20": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(Gql__input_Xrc20Action()),
				},
			},
		})
	}
	return gql__input_XRC20ByPageResponse
}

func Gql__input_XRC20ByPageRequest() *graphql.InputObject {
	if gql__input_XRC20ByPageRequest == nil {
		gql__input_XRC20ByPageRequest = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Api_Input_XRC20ByPageRequest",
			Fields: graphql.InputObjectConfigFieldMap{
				"pagination": &graphql.InputObjectFieldConfig{
					Type: pagination.Gql__input_Pagination(),
				},
			},
		})
	}
	return gql__input_XRC20ByPageRequest
}

func Gql__input_XRC20ByContractAddressResponse() *graphql.InputObject {
	if gql__input_XRC20ByContractAddressResponse == nil {
		gql__input_XRC20ByContractAddressResponse = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Api_Input_XRC20ByContractAddressResponse",
			Fields: graphql.InputObjectConfigFieldMap{
				"exist": &graphql.InputObjectFieldConfig{
					Type: graphql.Boolean,
				},
				"count": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"xrc20": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(Gql__input_Xrc20Action()),
				},
			},
		})
	}
	return gql__input_XRC20ByContractAddressResponse
}

func Gql__input_XRC20ByContractAddressRequest() *graphql.InputObject {
	if gql__input_XRC20ByContractAddressRequest == nil {
		gql__input_XRC20ByContractAddressRequest = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Api_Input_XRC20ByContractAddressRequest",
			Fields: graphql.InputObjectConfigFieldMap{
				"address": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"pagination": &graphql.InputObjectFieldConfig{
					Type: pagination.Gql__input_Pagination(),
				},
			},
		})
	}
	return gql__input_XRC20ByContractAddressRequest
}

func Gql__input_XRC20ByAddressResponse() *graphql.InputObject {
	if gql__input_XRC20ByAddressResponse == nil {
		gql__input_XRC20ByAddressResponse = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Api_Input_XRC20ByAddressResponse",
			Fields: graphql.InputObjectConfigFieldMap{
				"exist": &graphql.InputObjectFieldConfig{
					Type: graphql.Boolean,
				},
				"count": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"xrc20": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(Gql__input_Xrc20Action()),
				},
			},
		})
	}
	return gql__input_XRC20ByAddressResponse
}

func Gql__input_XRC20ByAddressRequest() *graphql.InputObject {
	if gql__input_XRC20ByAddressRequest == nil {
		gql__input_XRC20ByAddressRequest = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Api_Input_XRC20ByAddressRequest",
			Fields: graphql.InputObjectConfigFieldMap{
				"address": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"pagination": &graphql.InputObjectFieldConfig{
					Type: pagination.Gql__input_Pagination(),
				},
			},
		})
	}
	return gql__input_XRC20ByAddressRequest
}

func Gql__input_XRC20AddressesResponse() *graphql.InputObject {
	if gql__input_XRC20AddressesResponse == nil {
		gql__input_XRC20AddressesResponse = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Api_Input_XRC20AddressesResponse",
			Fields: graphql.InputObjectConfigFieldMap{
				"exist": &graphql.InputObjectFieldConfig{
					Type: graphql.Boolean,
				},
				"count": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"addresses": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.String),
				},
			},
		})
	}
	return gql__input_XRC20AddressesResponse
}

func Gql__input_XRC20AddressesRequest() *graphql.InputObject {
	if gql__input_XRC20AddressesRequest == nil {
		gql__input_XRC20AddressesRequest = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Api_Input_XRC20AddressesRequest",
			Fields: graphql.InputObjectConfigFieldMap{
				"pagination": &graphql.InputObjectFieldConfig{
					Type: pagination.Gql__input_Pagination(),
				},
			},
		})
	}
	return gql__input_XRC20AddressesRequest
}

// graphql__resolver_XRC20Service is a struct for making query, mutation and resolve fields.
// This struct must be implemented runtime.SchemaBuilder interface.
type graphql__resolver_XRC20Service struct {

	// Automatic connection host
	host string

	// grpc dial options
	dialOptions []grpc.DialOption

	// grpc client connection.
	// this connection may be provided by user
	conn *grpc.ClientConn
}

// new_graphql_resolver_XRC20Service creates pointer of service struct
func new_graphql_resolver_XRC20Service(conn *grpc.ClientConn) *graphql__resolver_XRC20Service {
	return &graphql__resolver_XRC20Service{
		conn:        conn,
		host:        "localhost:50051",
		dialOptions: []grpc.DialOption{},
	}
}

// CreateConnection() returns grpc connection which user specified or newly connected and closing function
func (x *graphql__resolver_XRC20Service) CreateConnection(ctx context.Context) (*grpc.ClientConn, func(), error) {
	// If x.conn is not nil, user injected their own connection
	if x.conn != nil {
		return x.conn, func() {}, nil
	}

	// Otherwise, this handler opens connection with specified host
	conn, err := grpc.DialContext(ctx, x.host, x.dialOptions...)
	if err != nil {
		return nil, nil, err
	}
	return conn, func() { conn.Close() }, nil
}

// GetQueries returns acceptable graphql.Fields for Query.
func (x *graphql__resolver_XRC20Service) GetQueries(conn *grpc.ClientConn) graphql.Fields {
	return graphql.Fields{
		"XRC20ByAddress": &graphql.Field{
			Type: Gql__type_XRC20ByAddressResponse(),
			Args: graphql.FieldConfigArgument{
				"address": &graphql.ArgumentConfig{
					Type: graphql.String,
				},
				"pagination": &graphql.ArgumentConfig{
					Type: pagination.Gql__input_Pagination(),
				},
			},
			Resolve: func(p graphql.ResolveParams) (interface{}, error) {
				var req XRC20ByAddressRequest
				if err := runtime.MarshalRequest(p.Args, &req, false); err != nil {
					return nil, errors.Wrap(err, "Failed to marshal request for XRC20ByAddress")
				}
				client := NewXRC20ServiceClient(conn)
				resp, err := client.XRC20ByAddress(p.Context, &req)
				if err != nil {
					return nil, errors.Wrap(err, "Failed to call RPC XRC20ByAddress")
				}
				return resp, nil
			},
		},
		"XRC20ByContractAddress": &graphql.Field{
			Type: Gql__type_XRC20ByContractAddressResponse(),
			Args: graphql.FieldConfigArgument{
				"address": &graphql.ArgumentConfig{
					Type: graphql.String,
				},
				"pagination": &graphql.ArgumentConfig{
					Type: pagination.Gql__input_Pagination(),
				},
			},
			Resolve: func(p graphql.ResolveParams) (interface{}, error) {
				var req XRC20ByContractAddressRequest
				if err := runtime.MarshalRequest(p.Args, &req, false); err != nil {
					return nil, errors.Wrap(err, "Failed to marshal request for XRC20ByContractAddress")
				}
				client := NewXRC20ServiceClient(conn)
				resp, err := client.XRC20ByContractAddress(p.Context, &req)
				if err != nil {
					return nil, errors.Wrap(err, "Failed to call RPC XRC20ByContractAddress")
				}
				return resp, nil
			},
		},
		"XRC20ByPage": &graphql.Field{
			Type: Gql__type_XRC20ByPageResponse(),
			Args: graphql.FieldConfigArgument{
				"pagination": &graphql.ArgumentConfig{
					Type: pagination.Gql__input_Pagination(),
				},
			},
			Resolve: func(p graphql.ResolveParams) (interface{}, error) {
				var req XRC20ByPageRequest
				if err := runtime.MarshalRequest(p.Args, &req, false); err != nil {
					return nil, errors.Wrap(err, "Failed to marshal request for XRC20ByPage")
				}
				client := NewXRC20ServiceClient(conn)
				resp, err := client.XRC20ByPage(p.Context, &req)
				if err != nil {
					return nil, errors.Wrap(err, "Failed to call RPC XRC20ByPage")
				}
				return resp, nil
			},
		},
		"XRC20Addresses": &graphql.Field{
			Type: Gql__type_XRC20AddressesResponse(),
			Args: graphql.FieldConfigArgument{
				"pagination": &graphql.ArgumentConfig{
					Type: pagination.Gql__input_Pagination(),
				},
			},
			Resolve: func(p graphql.ResolveParams) (interface{}, error) {
				var req XRC20AddressesRequest
				if err := runtime.MarshalRequest(p.Args, &req, false); err != nil {
					return nil, errors.Wrap(err, "Failed to marshal request for XRC20Addresses")
				}
				client := NewXRC20ServiceClient(conn)
				resp, err := client.XRC20Addresses(p.Context, &req)
				if err != nil {
					return nil, errors.Wrap(err, "Failed to call RPC XRC20Addresses")
				}
				return resp, nil
			},
		},
		"XRC20TokenHolderAddresses": &graphql.Field{
			Type: Gql__type_XRC20TokenHolderAddressesResponse(),
			Args: graphql.FieldConfigArgument{
				"tokenAddress": &graphql.ArgumentConfig{
					Type: graphql.String,
				},
				"pagination": &graphql.ArgumentConfig{
					Type: pagination.Gql__input_Pagination(),
				},
			},
			Resolve: func(p graphql.ResolveParams) (interface{}, error) {
				var req XRC20TokenHolderAddressesRequest
				if err := runtime.MarshalRequest(p.Args, &req, false); err != nil {
					return nil, errors.Wrap(err, "Failed to marshal request for XRC20TokenHolderAddresses")
				}
				client := NewXRC20ServiceClient(conn)
				resp, err := client.XRC20TokenHolderAddresses(p.Context, &req)
				if err != nil {
					return nil, errors.Wrap(err, "Failed to call RPC XRC20TokenHolderAddresses")
				}
				return resp, nil
			},
		},
	}
}

// GetMutations returns acceptable graphql.Fields for Mutation.
func (x *graphql__resolver_XRC20Service) GetMutations(conn *grpc.ClientConn) graphql.Fields {
	return graphql.Fields{}
}

// Register package divided graphql handler "without" *grpc.ClientConn,
// therefore gRPC connection will be opened and closed automatically.
// Occasionally you may worry about open/close performance for each handling graphql request,
// then you can call RegisterXRC20ServiceGraphqlHandler with *grpc.ClientConn manually.
func RegisterXRC20ServiceGraphql(mux *runtime.ServeMux) error {
	return RegisterXRC20ServiceGraphqlHandler(mux, nil)
}

// Register package divided graphql handler "with" *grpc.ClientConn.
// this function accepts your defined grpc connection, so that we reuse that and never close connection inside.
// You need to close it maunally when application will terminate.
// Otherwise, you can specify automatic opening connection with ServiceOption directive:
//
// service XRC20Service {
//    option (graphql.service) = {
//        host: "host:port"
//        insecure: true or false
//    };
//
//    ...with RPC definitions
// }
func RegisterXRC20ServiceGraphqlHandler(mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return mux.AddHandler(new_graphql_resolver_XRC20Service(conn))
}
